### PR TITLE
reduce crypto glitches and ignore crypto errors

### LINKED ISSUE #515: All peers become "unestablished"
I'm not sure if it is the current weave image that was pushed out last week or if it is testing more instances with it or what; but essentially at one point spinning up weave instances or if we restart weave instances (ie weave stop, let it be dead for a while then spin it up again; basically testing a rolling update situation or network interruption/system restart/what have you), the weave peers start having connectivity issues and then eventually basically all weave peers across all weave instances show up as "unestablished."  Also containers connected via the weave instance isn't able to route traffic while this is happening...  Sometimes waiting a couple hours resolves the issues, but often it seems the only way to recover is to just shutting down instances until things are happy again.  We are very eager to utilize weave, but we can't proceed with weave in this state...

I'm currently on version:
```
# weave version
weave script (unreleased version)
weave router git-b00be096f78a
Unable to find zettio/weavedns:latest image.
```

I'm also working on EC2 instances inside a VPC, and all EC2 instances are in the same reason and shouldn't have issues communicating with on another....  We are currently trying to wire up 12 instances together (I have set  -connlimit 50); 

The last time it happened, on one of my servers, I saw

```
weave 2015/04/05 09:04:58.507960 ->[7a:4c:0a:20:2e:0b(load-xxx-instance2)]: Effective PMTU set to 8921
weave 2015/04/05 09:04:58.585725 ->[7a:4c:0a:20:2e:0b(load-xxx-instance2)]: Effective PMTU verified at 8921
weave 2015/04/05 09:05:40.208252 Discovered remote MAC 92:ba:fd:55:a1:5a at 7a:4c:0a:20:2e:0b(load-xxx-instance2)
weave 2015/04/05 09:05:55.784310 Discovered remote MAC 6a:9d:16:ad:36:82 at 7a:ce:9d:00:a1:1d(load-logstash-instance2)
weave 2015/04/05 09:06:11.643978 ->[10.0.2.161:41710] connection accepted
weave 2015/04/05 09:06:11.644630 ->[10.0.2.161:41710] connection shutting down due to error during handshake: Already have connection to 7a:b7:0a:c0:f3:f0(dev-yyy-instance3) at 10.0.2.161:6783
weave 2015/04/05 09:08:25.917098 ->[10.0.6.155:46605] connection accepted
weave 2015/04/05 09:08:25.917756 ->[10.0.6.155:46605] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:25.917825 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added (new peer)
weave 2015/04/05 09:08:25.932458 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection fully established
weave 2015/04/05 09:08:25.933251 EMSGSIZE on send, expecting PMTU update (IP packet was 60082 bytes, payload was 60074 bytes)
weave 2015/04/05 09:08:25.933283 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: Effective PMTU set to 8921
weave 2015/04/05 09:08:26.015285 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: Effective PMTU verified at 8921
weave 2015/04/05 09:08:48.961003 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection shutting down due to error: read tcp4 10.0.2.5:40315: connection reset by peer
weave 2015/04/05 09:08:48.961140 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:48.962933 ->[10.0.2.5:6783] attempting connection
weave 2015/04/05 09:08:48.963378 ->[10.0.2.5:44127] connection accepted
weave 2015/04/05 09:08:48.963923 ->[10.0.2.5:44127] completed handshake with 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:48.964479 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection added
weave 2015/04/05 09:08:48.966333 ->[10.0.2.5:6783] completed handshake with 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:48.967129 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection shutting down due to error: read tcp4 10.0.2.5:44127: connection reset by peer
weave 2015/04/05 09:08:48.967307 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:48.971950 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection added
weave 2015/04/05 09:08:50.047939 ->[10.0.2.5:44142] connection accepted
weave 2015/04/05 09:08:50.048831 ->[10.0.2.5:44142] completed handshake with 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:50.048955 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:3d:12:77:03:8b(dev-xxx-instance1) added to 7a:1e:06:5f:50:07(dev-yyy-instance1)
weave 2015/04/05 09:08:51.195830 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:51.967899 ->[10.0.2.5:44154] connection accepted
weave 2015/04/05 09:08:51.968583 ->[10.0.2.5:44154] completed handshake with 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:51.968694 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:3d:12:77:03:8b(dev-xxx-instance1) added to 7a:1e:06:5f:50:07(dev-yyy-instance1)
weave 2015/04/05 09:08:52.193015 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:53.168011 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:53.196992 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:53.409856 ->[10.0.6.42:59344] connection accepted
weave 2015/04/05 09:08:53.409887 ->[7a:0e:0c:7a:dd:fe(dev-zzz-instance1)]: connection shutting down due to error: read tcp4 10.0.6.42:56274: connection reset by peer
weave 2015/04/05 09:08:53.410055 ->[7a:0e:0c:7a:dd:fe(dev-zzz-instance1)]: connection deleted
weave 2015/04/05 09:08:53.410694 ->[10.0.6.42:59344] completed handshake with 7a:0e:0c:7a:dd:fe(dev-zzz-instance1)
weave 2015/04/05 09:08:53.410870 ->[7a:0e:0c:7a:dd:fe(dev-zzz-instance1)]: connection added
weave 2015/04/05 09:08:54.169060 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:54.169121 Received packet for unknown destination: 7a:0e:0c:7a:dd:fe(dev-zzz-instance1)
weave 2015/04/05 09:08:54.659941 ->[10.0.2.5:44180] connection accepted
weave 2015/04/05 09:08:54.660499 ->[10.0.2.5:44180] completed handshake with 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:54.660559 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:54.660632 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection added (new peer)
weave 2015/04/05 09:08:54.663561 ->[7a:3d:12:77:03:8b(dev-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:3d:12:77:03:8b(dev-xxx-instance1) added to 7a:1e:06:5f:50:07(dev-yyy-instance1)
weave 2015/04/05 09:08:54.663941 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:54.857093 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:55.853065 Received packet for unknown destination: 7a:3d:12:77:03:8b(dev-xxx-instance1)
```

Looks like it was able to connect to the new server "demo-xxx-instance1" then afterwards machines started registering "Received packet for unknown destination"

On the first server that seemingly had issues, dev-xxx-instance1, it's logs have:

```
weave 2015/04/05 09:08:25.923434 ->[10.0.6.155:36708] connection accepted
weave 2015/04/05 09:08:25.925782 ->[10.0.6.155:6783] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:25.925918 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added (new peer)
weave 2015/04/05 09:08:25.935814 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection fully established
weave 2015/04/05 09:08:25.936201 EMSGSIZE on send, expecting PMTU update (IP packet was 60082 bytes, payload was 60074 bytes)
weave 2015/04/05 09:08:25.936296 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: Effective PMTU set to 8921
weave 2015/04/05 09:08:25.967294 ->[10.0.6.155:36708] connection shutting down due to error during handshake: Already have connection to 7a:35:ff:e0:ad:29(demo-xxx-instance1) at 10.0.6.155:6783
weave 2015/04/05 09:08:25.983811 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: Failed to decode packet: decryption failed; Suspected replay attack detected when decrypting UDP packet
weave 2015/04/05 09:08:25.984022 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:25.987252 ->[10.0.6.155:6783] attempting connection
weave 2015/04/05 09:08:25.994715 ->[10.0.6.155:6783] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:25.995021 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added
weave 2015/04/05 09:08:26.496358 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: write tcp4 10.0.6.155:6783: connection reset by peer
weave 2015/04/05 09:08:26.497218 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:26.497509 ->[10.0.6.155:6783] attempting connection
weave 2015/04/05 09:08:26.504692 ->[10.0.6.155:6783] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:26.505891 ->[10.0.6.155:36726] connection accepted
weave 2015/04/05 09:08:26.515607 ->[10.0.6.155:36726] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:26.528760 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added
weave 2015/04/05 09:08:26.528887 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:26.529033 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added
weave 2015/04/05 09:08:26.541359 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:35:ff:e0:ad:29(demo-xxx-instance1) added to 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:26.606384 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: write tcp4 10.0.6.155:36726: connection reset by peer
weave 2015/04/05 09:08:26.606549 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:26.615125 ->[10.0.6.155:6783] attempting connection
weave 2015/04/05 09:08:26.615313 ->[10.0.6.155:36733] connection accepted
weave 2015/04/05 09:08:26.616143 ->[10.0.6.155:36733] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:26.621874 ->[10.0.6.155:6783] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:26.630949 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added
weave 2015/04/05 09:08:26.642065 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:35:ff:e0:ad:29(demo-xxx-instance1) added to 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:27.121552 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: read tcp4 10.0.6.155:36733: connection reset by peer
weave 2015/04/05 09:08:27.121797 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:27.123131 ->[10.0.6.155:6783] attempting connection
weave 2015/04/05 09:08:27.127139 ->[10.0.6.155:36743] connection accepted
weave 2015/04/05 09:08:27.128378 ->[10.0.6.155:6783] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:27.129155 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection added
weave 2015/04/05 09:08:27.132866 ->[10.0.6.155:36743] completed handshake with 7a:35:ff:e0:ad:29(demo-xxx-instance1)
weave 2015/04/05 09:08:27.133033 ->[7a:35:ff:e0:ad:29(demo-xxx-instance1)]: connection shutting down due to error: Multiple connections to 7a:35:ff:e0:ad:29(demo-xxx-instance1) added to 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:48.199385 ->[7a:a3:3d:ff:e3:9b(load-xxx-instance1)]: connection shutting down due to error: timed out waiting for UDP heartbeat
weave 2015/04/05 09:08:48.199527 ->[7a:a3:3d:ff:e3:9b(load-xxx-instance1)]: connection deleted
weave 2015/04/05 09:08:48.201342 ->[10.0.2.189:6783] attempting connection
weave 2015/04/05 09:08:48.202971 ->[10.0.2.189:42206] connection accepted
weave 2015/04/05 09:08:48.204723 ->[10.0.2.189:42206] completed handshake with 7a:a3:3d:ff:e3:9b(load-xxx-instance1)
weave 2015/04/05 09:08:48.205011 ->[7a:a3:3d:ff:e3:9b(load-xxx-instance1)]: connection added
weave 2015/04/05 09:08:48.206166 ->[10.0.2.189:6783] completed handshake with 7a:a3:3d:ff:e3:9b(load-xxx-instance1)
weave 2015/04/05 09:08:48.207652 ->[7a:a3:3d:ff:e3:9b(load-xxx-instance1)]: connection shutting down due to error: write tcp4 10.0.2.189:6783: connection reset by peer
weave 2015/04/05 09:08:48.800278 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection shutting down due to error: timed out waiting for UDP heartbeat
weave 2015/04/05 09:08:48.800409 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection deleted
weave 2015/04/05 09:08:48.802190 ->[10.0.6.78:6783] attempting connection
weave 2015/04/05 09:08:48.806310 ->[10.0.6.78:44369] connection accepted
weave 2015/04/05 09:08:48.807851 ->[10.0.6.78:44369] completed handshake with 7a:44:3a:8c:91:fb(load-xxx-instance3)
weave 2015/04/05 09:08:48.807959 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection added
weave 2015/04/05 09:08:48.808631 ->[10.0.6.78:6783] completed handshake with 7a:44:3a:8c:91:fb(load-xxx-instance3)
weave 2015/04/05 09:08:48.811043 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection deleted
weave 2015/04/05 09:08:48.811107 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection added
weave 2015/04/05 09:08:48.813256 ->[7a:44:3a:8c:91:fb(load-xxx-instance3)]: connection shutting down due to error: Multiple connections to 7a:44:3a:8c:91:fb(load-xxx-instance3) added to 7a:3d:12:77:03:8b(dev-xxx-instance1)
weave 2015/04/05 09:08:48.847521 ->[7a:4c:0a:20:2e:0b(load-xxx-instance2)]: connection shutting down due to error: timed out waiting for UDP heartbeat
weave 2015/04/05 09:08:48.847570 ->[7a:4c:0a:20:2e:0b(load-xxx-instance2)]: connection deleted
weave 2015/04/05 09:08:48.849113 ->[10.0.2.32:6783] attempting connection
weave 2015/04/05 09:08:48.871939 ->[10.0.2.32:6783] completed handshake with 7a:4c:0a:20:2e:0b(load-xxx-instance2)
weave 2015/04/05 09:08:48.872131 ->[7a:4c:0a:20:2e:0b(load-xxx-instance2)]: connection added
```

I also grabbed the dump from doing SIGQUIT:

```
weave 2015/04/05 10:35:00.572950 === received SIGQUIT ===
*** goroutine dump...
goroutine 1 [running]:
main.handleSignals(0xc209116200)
	/home/matthias/go/src/github.com/zettio/weave/weaver/main.go:209 +0x30c
main.main()
	/home/matthias/go/src/github.com/zettio/weave/weaver/main.go:128 +0x124d

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 122 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 18 [select]:
github.com/zettio/weave/router.(*LocalPeer).actorLoop(0xc20910e180, 0xc2091260c0)
	/home/matthias/go/src/github.com/zettio/weave/router/local_peer.go:157 +0x101
created by github.com/zettio/weave/router.(*LocalPeer).Start
	/home/matthias/go/src/github.com/zettio/weave/router/local_peer.go:25 +0x7e

goroutine 19 [chan receive]:
github.com/zettio/weave/router.(*Routes).actorLoop(0xc2091142c0, 0xc209126120)
	/home/matthias/go/src/github.com/zettio/weave/router/routes.go:87 +0x47
created by github.com/zettio/weave/router.(*Routes).Start
	/home/matthias/go/src/github.com/zettio/weave/router/routes.go:32 +0x7e

goroutine 20 [select]:
github.com/zettio/weave/router.(*ConnectionMaker).queryLoop(0xc209112300, 0xc209126180)
	/home/matthias/go/src/github.com/zettio/weave/router/connection_maker.go:99 +0x162
created by github.com/zettio/weave/router.(*ConnectionMaker).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection_maker.go:45 +0x7e

goroutine 21 [chan receive]:
github.com/zettio/weave/router.(*NaClDecryptorInstance).advanceState(0xc20a919290, 0xc209f00000, 0xa, 0x0, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/crypto.go:378 +0xd9
github.com/zettio/weave/router.(*NaClDecryptor).decrypt(0xc20a91ce20, 0xc2094618c0, 0x36, 0x36, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/crypto.go:353 +0x11c
github.com/zettio/weave/router.(*NaClDecryptor).IterateFrames(0xc20a91ce20, 0xc2094618c0, 0x36, 0x36, 0xc20946d230, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/crypto.go:336 +0x72
github.com/zettio/weave/router.(*Router).udpReader(0xc209116200, 0xc209124028, 0x7f8dadf5d820, 0xc209124018)
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:242 +0x64c
created by github.com/zettio/weave/router.(*Router).listenUDP
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:212 +0x324

goroutine 22 [IO wait]:
net.(*pollDesc).Wait(0xc20912a1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20912a1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20912a150, 0x0, 0x7f8daf999730, 0xc208e4b2e8)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc209124048, 0xc20a2740b8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/zettio/weave/router.func·026()
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:179 +0x5e
created by github.com/zettio/weave/router.(*Router).listenTCP
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:186 +0x2e4

goroutine 23 [syscall, locked to thread]:
code.google.com/p/gopacket/pcap._Cfunc_pcap_next_ex(0x2184f30, 0xc2091143e8, 0xc2091143f0, 0x0)
	/home/matthias/go/src/code.google.com/p/gopacket/pcap/:172 +0x43
code.google.com/p/gopacket/pcap.(*Handle).getNextBufPtrLocked(0xc2091143c0, 0xc20a278ef8, 0x0, 0x0)
	/home/matthias/go/src/code.google.com/p/gopacket/pcap/pcap.go:302 +0x6b
code.google.com/p/gopacket/pcap.(*Handle).ZeroCopyReadPacketData(0xc2091143c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/matthias/go/src/code.google.com/p/gopacket/pcap/pcap.go:334 +0xb0
github.com/zettio/weave/router.(*PcapIO).ReadPacket(0xc209124010, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/pcap.go:64 +0x67
github.com/zettio/weave/router.func·025()
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:114 +0x5d
created by github.com/zettio/weave/router.(*Router).sniff
	/home/matthias/go/src/github.com/zettio/weave/router/router.go:119 +0x40d

goroutine 24 [IO wait]:
net.(*pollDesc).Wait(0xc20912b170, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20912b170, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20912b110, 0x0, 0x7f8daf999730, 0xc20900c720)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2091240b0, 0x559ade, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net/http.tcpKeepAliveListener.Accept(0xc2091240b0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1976 +0x4c
net/http.(*Server).Serve(0xc209126540, 0x7f8dadf5eea0, 0xc2091240b0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.(*Server).ListenAndServe(0xc209126540, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1718 +0x154
net/http.ListenAndServe(0xc20911e840, 0x5, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1808 +0xba
main.handleHTTP(0xc209116200)
	/home/matthias/go/src/github.com/zettio/weave/weaver/main.go:195 +0x723
created by main.main
	/home/matthias/go/src/github.com/zettio/weave/weaver/main.go:127 +0x123d

goroutine 33562 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc20a54fb40)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33557 [IO wait]:
net.(*pollDesc).Wait(0xc209a0aed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209a0aed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc209a0ae70, 0xc20a283000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208dfe7a8)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209cb8bc8, 0xc20a283000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20a970420)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20a970420, 0xc208d70560, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc20a970420, 0xc208d70560, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc20a970420, 0xc208d70560, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc20a970420, 0xc208d70560, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc20a280380, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc20a280380, 0xc2098a1100, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc20a280380, 0x7cfee0, 0xc2098a1120, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc20a280380, 0x7cfee0, 0xc2098a1120, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc209e17340, 0xc20a280380)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33661 [IO wait]:
net.(*pollDesc).Wait(0xc20a0cafb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a0cafb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a0caf50, 0xc209f8d000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e15220)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a2740b8, 0xc209f8d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc209324c60)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc209324c60, 0xc208e713e0, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc209324c60, 0xc208e713e0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc209324c60, 0xc208e713e0, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc209324c60, 0xc208e713e0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209ed2e80, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209ed2e80, 0xc20a167b00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209ed2e80, 0x7cfee0, 0xc20a167b00, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209ed2e80, 0x7cfee0, 0xc20a167b00, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20a0f20e0, 0xc209ed2e80)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33672 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc209405c80, 0xc209a47200, 0xc209a47260, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33590 [IO wait]:
net.(*pollDesc).Wait(0xc20a28bfe0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a28bfe0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a28bf80, 0xc20a077000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e0ada0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209b9fde8, 0xc20a077000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20a070420)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20a070420, 0xc208d3f960, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc20a070420, 0xc208d3f960, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc20a070420, 0xc208d3f960, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc20a070420, 0xc208d3f960, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209f6f480, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209f6f480, 0xc209284800, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209f6f480, 0x7cfee0, 0xc209284800, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209f6f480, 0x7cfee0, 0xc209284800, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20954c700, 0xc209f6f480)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33433 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209f1c260)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33454 [IO wait]:
net.(*pollDesc).Wait(0xc20931ffe0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20931ffe0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20931ff80, 0xc209142000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e05be0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20aa19f28, 0xc209142000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2094a3920)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2094a3920, 0xc208fa7d20, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc2094a3920, 0xc208fa7d20, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc2094a3920, 0xc208fa7d20, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc2094a3920, 0xc208fa7d20, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209ca9300, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209ca9300, 0xc209285d00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209ca9300, 0x7cfee0, 0xc209285d40, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209ca9300, 0x7cfee0, 0xc209285d40, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20a6600e0, 0xc209ca9300)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33606 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20a281580, 0xc20a26acc0, 0xc20a26ad20, 0xc209e175e0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33591 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20a194380, 0xc20930ff20, 0xc20930ff80, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33602 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc20959de00)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33604 [IO wait]:
net.(*pollDesc).Wait(0xc20a91af40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a91af40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a91aee0, 0xc20a4af000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e2df60)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209cb9f98, 0xc20a4af000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2092f19e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2092f19e0, 0xc208cc26a0, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc2092f19e0, 0xc208cc26a0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc2092f19e0, 0xc208cc26a0, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc2092f19e0, 0xc208cc26a0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc20a280e80, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc20a280e80, 0xc2092c8000, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc20a280e80, 0x7cfee0, 0xc2092c80e0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc20a280e80, 0x7cfee0, 0xc2092c80e0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc209e17500, 0xc20a280e80)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33605 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20a281500, 0xc20a26ac00, 0xc20a26ac60, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33630 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc20a754720)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33455 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20975b080, 0xc20a149080, 0xc20a1490e0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33607 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209f5a0a0)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33643 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20a0f20e0, 0xc209a46180, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20a0f20e0, 0xc209a46180, 0xc209a461e0, 0x8ea401)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33614 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209bda080)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33618 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20962d100, 0xc209598300, 0xc209598360, 0xc20a0f29a0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33592 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20a194400, 0xc20a1a8000, 0xc20a1a8060, 0xc20a6607e0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33669 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20a0f28c0, 0xc209a46420, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20a0f28c0, 0xc209a46420, 0xc209a46480, 0x8ea400)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33673 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc209405d00, 0xc209a472c0, 0xc209a47320, 0xc20a0f2fc0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33438 [IO wait]:
net.(*pollDesc).Wait(0xc2097b1b10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2097b1b10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2097b1ab0, 0xc20a072000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e259e0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a275170, 0xc20a072000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20a023080)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20a023080, 0xc208d7d5e0, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc20a023080, 0xc208d7d5e0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc20a023080, 0xc208d7d5e0, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc20a023080, 0xc208d7d5e0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc2097aca00, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc2097aca00, 0xc209888800, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc2097aca00, 0x7cfee0, 0xc2098888e0, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc2097aca00, 0x7cfee0, 0xc2098888e0, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20a660460, 0xc2097aca00)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33622 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20a0f2c40, 0xc209aca180, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20a0f2c40, 0xc209aca180, 0xc209aca1e0, 0x8ea401)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33663 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209ea4500)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33635 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209ae3ec0)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33551 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20954c540, 0xc208045f80, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20954c540, 0xc208045f80, 0xc20a070000, 0x8ea400)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33470 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20a6600e0, 0xc2094a3800, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20a6600e0, 0xc2094a3800, 0xc2094a3860, 0x8ea400)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33456 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20975b100, 0xc20a149140, 0xc20a1491a0, 0xc209e167e0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33603 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc209e17500, 0xc2092f18c0, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc209e17500, 0xc2092f18c0, 0xc2092f1920, 0x8ea400)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33440 [IO wait]:
net.(*pollDesc).Wait(0xc209eca060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209eca060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc209eca000, 0xc209fb7000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e03ae0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209b9fda8, 0xc209fb7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc20a0700c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc20a0700c0, 0xc208d3ec64, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc20a0700c0, 0xc208d3ec64, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc20a0700c0, 0xc208d3ec64, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc20a0700c0, 0xc208d3ec64, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209f6f200, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209f6f200, 0xc2098a0b00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209f6f200, 0x7cfee0, 0xc2098a0b00, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209f6f200, 0x7cfee0, 0xc2098a0b00, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20954c540, 0xc209f6f200)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33584 [chan receive]:
github.com/zettio/weave/router.(*GossipSender).run(0xc209ae3c20)
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:56 +0x54
created by github.com/zettio/weave/router.(*GossipSender).Start
	/home/matthias/go/src/github.com/zettio/weave/router/gossip.go:51 +0x6f

goroutine 33441 [select]:
github.com/zettio/weave/router.(*Forwarder).run(0xc20962d080, 0xc209598240, 0xc2095982a0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:244 +0x457
created by github.com/zettio/weave/router.(*Forwarder).Start
	/home/matthias/go/src/github.com/zettio/weave/router/forwarder.go:220 +0xfc

goroutine 33671 [IO wait]:
net.(*pollDesc).Wait(0xc209a44fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209a44fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc209a44f50, 0xc209929000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208e302a0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc209705b10, 0xc209929000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc209a46540)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc209a46540, 0xc2099322a0, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc209a46540, 0xc2099322a0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc209a46540, 0xc2099322a0, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc209a46540, 0xc2099322a0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc209405000, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc209405000, 0xc20a0cde00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc209405000, 0x7cfee0, 0xc20a0cde20, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc209405000, 0x7cfee0, 0xc20a0cde20, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20a0f28c0, 0xc209405000)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33599 [IO wait]:
net.(*pollDesc).Wait(0xc20a0a1b80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a0a1b80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a0a1b20, 0xc20a2b2000, 0x1000, 0x1000, 0x0, 0x7f8daf999730, 0xc208df87a0)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a375a20, 0xc20a2b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc209aca360)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc209aca360, 0xc208c54320, 0x1, 0x9, 0x100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f8dadf5d690, 0xc209aca360, 0xc208c54320, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f8dadf5d690, 0xc209aca360, 0xc208c54320, 0x1, 0x9, 0x40, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x6d
encoding/gob.decodeUintReader(0x7f8dadf5d690, 0xc209aca360, 0xc208c54320, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc20962de00, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:76 +0x55
encoding/gob.(*Decoder).decodeTypeSequence(0xc20962de00, 0xc2098a1e00, 0x16)
	/usr/local/go/src/encoding/gob/decoder.go:140 +0x47
encoding/gob.(*Decoder).DecodeValue(0xc20962de00, 0x7cfee0, 0xc2098a1e60, 0x16, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:208 +0x192
encoding/gob.(*Decoder).Decode(0xc20962de00, 0x7cfee0, 0xc2098a1e60, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/decoder.go:185 +0x297
github.com/zettio/weave/router.(*LocalConnection).receiveTCP(0xc20a0f2c40, 0xc20962de00)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:412 +0x152
github.com/zettio/weave/router.func·005()
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:308 +0x69
created by github.com/zettio/weave/router.(*LocalConnection).run
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:309 +0x518

goroutine 33553 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20954c700, 0xc20a070300, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20954c700, 0xc20a070300, 0xc20a070360, 0x8ea400)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33556 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc209e17340, 0xc20a970300, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc209e17340, 0xc20a970300, 0xc20a970360, 0x8ea401)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

goroutine 33512 [select]:
github.com/zettio/weave/router.(*LocalConnection).actorLoop(0xc20a660460, 0xc20a022de0, 0x0, 0x0)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:347 +0x2a2
github.com/zettio/weave/router.(*LocalConnection).run(0xc20a660460, 0xc20a022de0, 0xc20a022e40, 0x8ea401)
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:327 +0x8ba
created by github.com/zettio/weave/router.(*LocalConnection).Start
	/home/matthias/go/src/github.com/zettio/weave/router/connection.go:119 +0xdd

*** end
```

### PR DESCRIPTION
**Pull request by rade**
Closes #515.

I have filed #564 as a follow-up.

### CODE REVIEW

**Comment by rade** [comment]
With this change I can get `NUM_WEAVES=32 bin/multiweave launch -password pass -connlimit 100` to work just fine. Previously things would go wrong from 4, and *really* wrong at 7.

File: router/router.go [hunk 1]
```diff
@@ -250,15 +250,19 @@ func (router *Router) udpReader(conn *net.UDPConn, po PacketSink) {
...
-			}
-		} else {
-			checkWarn(err)
+		if err := relayConn.Decryptor.IterateFrames(packet, router.handleUDPPacketFunc(dec, sender, po)); err != nil {
+			// Errors during UDP packet decoding / processing are
+			// non-fatal. One common cause is that we receive and
+			// attempt to decrypt a "stray" packet. This can actually
+			// happen quite easily if there is some connection churn
+			// between two peers. After all, UDP isn't a
+			// connection-oriented protocol, yet we pretend it is.
```
Comment (bboreham) [inline router/router.go]: 'pretend it is' could be clarified.  Are you saying this code here makes assumptions?

Comment (rade) [inline router/router.go]: It's a general weave pretense. The control plane is constructed from TCP connections. The data plane from UDP "connections".
