### PR TITLE
Work around missing docker.sock in plugin-v2

### LINKED ISSUE #2906: Docker plugin-v2 can be started before /var/run/docker.sock is ready
If `/var/run/docker.sock` is not ready, plugin-v2 will fail silently to start:

```
16:07:48+01:00" level=info msg="Starting launch.sh" plugin=d4429df88c47efe094b7dd3c471aa7f4f61612e378814ad706c7b7d0
...
16:08:26.948417772+01:00" level=info msg="API listen on /var/run/docker.sock"
```

Worse than this is Docker reporting that the plugin is enabled:

```
$ docker plugin ls
ID                  NAME                           DESCRIPTION                   ENABLED
d4429df88c47        weaveworks/net-plugin:latest   Weave Net plugin for Docker   true
```

Reproduced with Docker 17.04.0-ce after restarting `docker.service`.

### PR DESCRIPTION
**Pull request by brb**
Current limitations:

* No `configure-arp`.
* Multicast can be enabled only for all networks (via `docker plugin set weaveworks/net-plugin WEAVE_MULTICAST=1` on each host).

Partly fixes #2906

### CODE REVIEW

File: prog/net-plugin/launch.sh [hunk 1]
```diff
@@ -16,42 +16,38 @@ echo "Starting launch.sh"
...
-/usr/bin/weaveutil is-swarm-manager 2>/dev/null || STATUS=$?
-if [ $STATUS -eq 0 ]; then
-    IS_SWARM_MANAGER=1
-elif [ $STATUS -eq 20 ]; then
-    echo "Host swarm is not \"active\"; exiting." >&2
-    exit 1
+# We need to get a list of Swarm nodes which might run the net-plugin:
+# - In the case of missing restart.sentinel, we assume that net-plugin has started
+#   for the first time via the docker-plugin cmd. So it's safe to request docker.sock.
+# - If restart.sentinel present, let weaver restore from it as docker.sock is not
```
Comment (bboreham) [inline prog/net-plugin/launch.sh]: Does this mean we will hang on to a peer in the list which has actually been removed from the Docker Swarm?
(this could be filed as a separate issue; doesn't have to be fixed here.)

File: plugin/net/driver.go [hunk 2]
```diff
@@ -189,11 +200,30 @@ func (driver *driver) findNetworkInfo(id string) (network, error) {
...
 	}
+
+	// plugin-v2 does not have access to docker.sock, so we cannot call Docker
+	// API for the network info.
+	if driver.isPluginV2 {
+		// safe to set, as isOurs used only by the watcher which is disabled for plugin-v2
+		network.isOurs = true
+		network.hasMulticastRoute = driver.forceMulticast
+
+		driver.Lock()
```
Comment (bboreham) [inline plugin/net/driver.go]: I think I might have omitted adding the data to the map, since we would just end up back here next time in that case.
Locking/adding in two places makes me nervous.

File: prog/weaveutil/swarm.go [hunk 3]
```diff
@@ -2,48 +2,32 @@ package main
...
 	for _, managerNode := range info.Swarm.RemoteManagers {
 		ip, err := ipFromAddr(managerNode.Addr)
 		if err != nil {
 			return errors.Wrap(err, "ipFromAddr")
 		}
-		fmt.Println(ip)
+		ips = append(ips, ip)
 	}
 
+	fmt.Println(strings.Join(ips, " "))
```
Comment (bboreham) [inline prog/weaveutil/swarm.go]: guessing this change was for easier testing?

Comment (brb) [inline prog/weaveutil/swarm.go]: Yep

File: plugin/net/driver.go (hunk 2 above)
Comment (brb) [inline plugin/net/driver.go]: Same though, I'm going to remove it.

File: prog/net-plugin/launch.sh (hunk 1 above)
Comment (brb) [inline prog/net-plugin/launch.sh]: Yep. I've created a separate issue for plugin-v2 improvements: https://github.com/weaveworks/weave/issues/2938

**Comment by brb** [comment]
PTAL.
