### PR TITLE
Try to compress too long replies (when forwarding).

### LINKED ISSUE #1306: "cannot unmarshal DNS message" using weavedns to resolve email-smtp.us-east-1.amazonaws.com
This bug shows a similar problem existed with consul dns:

https://github.com/golang/go/issues/11070

Looks like the following is happening:
- recursive dns is responding with a compressed answer, to fit in 512bytes
- miekg dns is uncompressing the answer transparently for us (https://github.com/miekg/dns/issues/216)
- we send the uncompresses answer on to the client, which then fails to parse it as its truncated.

### PR DESCRIPTION
**Pull request by inercia**
Fixes #1306 for 1.0.2

### CODE REVIEW

File: nameserver/server_test.go [hunk 1]
```diff
@@ -72,6 +75,18 @@ func TestUDPDNSServer(t *testing.T) {
...
+			header := makeHeader(m, &q, 300)
+			for {
+				if m.Len() > minUDPSize {
+					m.Compress = true
+					wt.AssertTrue(t, m.Len() <= minUDPSize, fmt.Sprintf("length: %d", m.Len()))
+					break
+				}
+				ip := address.Address(rand.Uint32()).IP4()
+				m.Answer = append(m.Answer, &dns.A{Hdr: *header, A: ip})
+			}
```
Comment (rade) [inline nameserver/server_test.go]:
```
for m.Len() <= minUDPSize {
...
}
m.Compress = true
wt.AssertTrue(...)
```

Comment (inercia) [inline nameserver/server_test.go]: Fixed. This was copy&pasted from #1307, so the same comment applies there...

**Comment by rade** [comment]
Please rebase, so this gets the CircleCI fix.
