### PR TITLE
Replace weave-local-pods ipset with physdev iptables rule

### LINKED ISSUE #3344: Replace weave-local-pods ipset with physdev iptables rule
We can get rid of the `weave-local-pods` ipset used by the weave-npc ingress rule `-A WEAVE-NPC -m set ! --match-set weave-local-pods dst -j ACCEPT` with `-A WEAVE-NPC -m physdev --physdev-out=vethwe-bridge -j ACCEPT`.

The former rule is insecure, as it might allow ingress traffic if the ipset is not properly maintained (e.g. due to crashing weave-npc as in https://github.com/weaveworks/weave/issues/3032#issuecomment-403397070) or if weave-npc lags behind processing updates from kube-apiserver.

### PR DESCRIPTION
**Pull request by murali-reddy**
by-pass ingress network policy chains and accept the packet if
destination is not one of the local pods

return the packets so the egress network policy chains are skipped
in case packet's source is not one of the local pods

Fixes #3344

### CODE REVIEW

File: prog/weave-npc/main.go [hunk 1]
```diff
@@ -125,28 +125,19 @@ func createBaseRules(ipt *iptables.IPTables, ips ipset.Interface) error {
 		}
 	}
 
+	// If the destination address is not any of the local pods, let it through
 	if err := ipt.Append(npc.TableFilter, npc.MainChain,
-		"-m", "state", "--state", "NEW", "-j", string(npc.DefaultChain)); err != nil {
+		"-m", "physdev", "--physdev-out=vethwe-bridge", "-j", "ACCEPT"); err != nil {
```
Comment (bboreham) [inline prog/weave-npc/main.go]: Hard-coding `vethwe-bridge` here seems wrong.  

Can this rule go in `weaver` where the rules go that drive traffic through the weave-npc chains?
Note that weave-npc is not otherwise tied to the specific implementation of Weave Net.

File: prog/weave-npc/main.go [hunk 2]
```diff
@@ -179,7 +170,7 @@ func createBaseRules(ipt *iptables.IPTables, ips ipset.Interface) error {
 
 	ruleSpecs := [][]string{
 		{"-m", "state", "--state", "RELATED,ESTABLISHED", "-j", "ACCEPT"},
-		{"-m", "state", "--state", "NEW", "-m", "set", "!", "--match-set", npc.LocalIpset, "src", "-j", "RETURN"},
+		{"-m", "physdev", "--physdev-in=vethwe-bridge", "-j", "RETURN"},
```
Comment (bboreham) [inline prog/weave-npc/main.go]: I'm not so sure this rule can move.  But again, hard-coding the device name is wrong.

File: prog/weave-npc/main.go (hunk 1 above)
Comment (murali-reddy) [reply prog/weave-npc/main.go]: removed hard-coded bridge name. PTAL

> Can this rule go in weaver where the rules go that drive traffic through the weave-npc chains?

No. moving it to `weaver` means this scenario will not work with kubenet etc. It fits in well in weave-npc as part of bunch of base rules that gets configured.

File: prog/weave-npc/main.go [hunk 3]
```diff
@@ -127,7 +128,7 @@ func createBaseRules(ipt *iptables.IPTables, ips ipset.Interface) error {
 
 	// If the destination address is not any of the local pods, let it through
 	if err := ipt.Append(npc.TableFilter, npc.MainChain,
-		"-m", "physdev", "--physdev-out=vethwe-bridge", "-j", "ACCEPT"); err != nil {
+		"-m", "physdev", "--physdev-out="+bridgeName, "-j", "ACCEPT"); err != nil {
```
Comment (brb) [inline prog/weave-npc/main.go]: I think `bridgeName` is a bit confusing here. IMO, `bridgePortName` would be better.

**Comment by murali-reddy** [comment]
Addressed all comments. PTAL

File: prog/weave-npc/main.go [hunk 4]
```diff
@@ -194,6 +186,17 @@ func createBaseRules(ipt *iptables.IPTables, ips ipset.Interface) error {
 		return err
 	}
 
+	// delete `weave-local-pods` ipset which is no longer used by weave-npc
+	weaveLocalPodExist, err := ipsetExist(ips, npc.LocalIpset)
+	if err != nil {
+		common.Log.Errorf("Failed to destroy ipset '%s'", npc.LocalIpset)
```
Comment (bboreham) [inline prog/weave-npc/main.go]: This message is a little misleading.  It's something like "failed to look for ipset".
