### PR TITLE
Keep flushing gossip until it's all gone

### LINKED ISSUE #885: gossip unit test failing intermittently
For example https://travis-ci.org/weaveworks/weave/builds/66049086:

````
--- FAIL: TestGossipTopology-2 (0.00s)
	util.go:134: Expected connections not found: from 02:00:00:02:00:00 to map[03:00:00:03:00:00:{}]
...
	github.com/weaveworks/weave/router.implTestGossipTopology(0xc2091082d0)
		/home/travis/gopath/src/github.com/weaveworks/weave/router/gossip_test.go:116 +0xc0b
````

Appears to be caused by topology updates being delivered on a different goroutine, which sometimes happens later than expected.  There is a 'FIXME' comment to the effect that `sendPendingGossip()` may not work.

`go test -race` reports many race conditions in this test, which may or may not be relevant.

### PR DESCRIPTION
**Pull request by bboreham**
Fix #885 more thoroughly, by looping across multiple routers until none of them have anything to say.

### CODE REVIEW

File: router/gossip_test.go [hunk 1]
```diff
@@ -32,6 +32,17 @@ func (conn *mockChannelConnection) SendProtocolMsg(protocolMsg ProtocolMsg) {
...
+func sendPendingGossip(routers ...*Router) {
+	done := false
+	// Loop until all routers report they didn't send anything
+	for !done {
+		done = true
+		for _, router := range routers {
+			done = !router.sendPendingGossip() && done
+		}
+	}
+}
```
Comment (rade) [inline router/gossip_test.go]:
````
func sendPendingGossip(routers ...*Router) {
	more := true
	// Loop until all routers report they didn't send anything
	for more {
		for _, router := range routers {
			more = router.sendPendingGossip() || more
		}
	}
}
````

Comment (rade) [inline router/gossip_test.go]: or, even better, `for more := true; more; {...}`

Comment (rade) [inline router/gossip_test.go]: ah, that's wrong. never mind.

Comment (rade) [inline router/gossip_test.go]:
````
func sendPendingGossip(routers ...*Router) {
	for sentSomething := true; sentSomething; {
		sentSomething = false
		for _, router := range routers {
			sentSomething  = router.sendPendingGossip() || sentSomething
		}
	}
}
````

File: router/gossip.go [hunk 2]
```diff
@@ -328,21 +329,23 @@ func (c *GossipChannel) log(args ...interface{}) {
...
-			sender.flush()
+			didSomething = sender.flush() || didSomething
 		}
 		for _, sender := range channel.broadcasters {
-			sender.flush()
+			didSomething = sender.flush() || didSomething
 		}
 		channel.Unlock()
 	}
+	return didSomething
```
Comment (rade) [inline router/gossip.go]: s/didSomething/sentSomething

File: router/gossip.go [hunk 3]
```diff
@@ -68,6 +68,7 @@ func (sender *GossipSender) run() {
 			case pending := <-sender.cell:
 				if pending != nil {
 					sender.send(pending)
+					ch <- true
```
Comment (rade) [inline router/gossip.go]: we don't actually need the nil check here.

Also, I reckon we should send true or false, and *not* close the channel.
