### PR TITLE
Proxy retry attaching containers

### LINKED ISSUE #1556: Proxy should retry attaching containers, after restarting
In case attaching them fails.

### PR DESCRIPTION
**Pull request by paulbellamy**
First experimental pass at having the proxy retry attaching containers if the attach fails.

Nice to haves:
* Detect if there are causes where a container will *never* successfully attach, and handle those.
* Some sort of back-off
* Should also combine multiple requests to attach the same container (by name or id).

Fixes #1556

### CODE REVIEW

**Comment by bboreham** [comment]
I rebased against master and updated to match recent changes.

**Comment by bboreham** [comment]
An example where we can be sure it's never going to attach is when `InspectContainer` returns `NoSuchContainer`.  I think that's more than a nice to have.

**Comment by bboreham** [comment]
Actually when `InspectContainer` returns `NoSuchContainer` the code will not retry, because it's not returned as an error from `attach()`.

**Comment by bboreham** [comment]
Currently the code will abandon retry on various conditions such as container not running.  I cannot think of any further conditions (once we get as far as calling `weave attach`) that should result in abandonment.  Doubtless we will find out in the field.

It will back off to one retry per minute which hopefully isn't too taxing on the machine.

File: proxy/proxy.go [hunk 1]
```diff
@@ -527,3 +557,47 @@ func (proxy *Proxy) updateContainerNetworkSettings(container jsonObject) error {
...
+		if len(pendingRetries) > 0 && nextRetry == nil {
+			nextRetry = time.After(pendingRetries[0].tryAfter.Sub(now))
+		}
+		select {
+		case <-nextRetry:
+			nextRetry = nil
+			a = pendingRetries[0]
+			pendingRetries = pendingRetries[1:]
+		case a = <-proxy.attachContainer:
+			for i, j := range pendingRetries { // remove any existing entry for same id
```
Comment (paulbellamy) [inline proxy/proxy.go]: We might accidentally remove `nextRetry`.

**Comment by paulbellamy** [comment]
The downside of using a `chan attachJob` is that attaching becomes single-threaded. I am debating if something in the rough vain of this would be more performant (and possibly simpler):
```Go
proxy.jobs = map[string]struct{ attachJob, *time.Timer }{
  containerID: struct{
    attachJob: ...,
    Timer: time.AfterFunc(func() {
      err := proxy.attach(containerID, attachJob.OrDie())
      ...
    }),
  },
}

...

func (proxy *Proxy) Stop() {
  for _, job := range proxy.jobs {
    job.Stop()
  }
}
```

File: proxy/proxy.go (hunk 1 above)
Comment (bboreham) [inline proxy/proxy.go]: You mean "the entry which was previously scheduled to be tried next"? Yes. It seemed innocuous to try the next one at that time.

It seems that `pendingRetries` could be left empty, which would be bad.

Perhaps best to set `nextRetry` to nil if an entry is taken out of the list, so it is re-computed next time round the loop.

**Comment by paulbellamy** [comment]
@bboreham Thoughts on https://github.com/weaveworks/weave/commit/1c7ff83810aad36e26fc75571ad5031d9da95a1e?

File: proxy/proxy.go [hunk 2]
```diff
@@ -72,10 +75,64 @@ type Proxy struct {
...
+
+	j := &attachJob{id: id, tryInterval: initialInterval}
+	j.timer = time.AfterFunc(time.Duration(0), func() {
+		if err := proxy.attach(id, false); err != nil {
+			j.reschedule()
+			return
+		}
+		proxy.notifyWaiters(id, nil)
+	})
+	proxy.attachJobs[id] = j
```
Comment (bboreham) [inline proxy/proxy.go]: I found it quite hard to figure out where the "retry loop" is.  The payload of `time.AfterFunc` gets called, calls `reschedule`, which calls `timer.Reset`, which causes the payload to be called again later.

It might be slightly easier to follow if the `Reset` call was inside the payload.

**Comment by bboreham** [comment]
Should we be re-enabling test 640 or something?

File: proxy/proxy.go (hunk 2 above)
Comment (paulbellamy) [inline proxy/proxy.go]: Yeah, inlining it does make it easier to follow, thanks. One thing I noticed while doing that, is that on line 92, in the case where an attach already exists, it short-circuits the current "retry timer", but doesn't reset the interval back down to 2 seconds. I'm debating if it should...

**Comment by paulbellamy** [comment]
640 still fails sporadically for me, so left it off...

**Comment by paulbellamy** [comment]
also, rebased.

**Comment by bboreham** [comment]
@paulbellamy is there any more to be done on this?

**Comment by paulbellamy** [comment]
Should be gtg.

**Comment by bboreham** [comment]
I think I'll squash the commits.
