### PR TITLE
Pass docker bridge ip to dns server, and filter it out of upstream dns ips.

### LINKED ISSUE #1343: DNS crashes if host resolv.conf contains docker0 bridge ip
We are trying to resolve container dns names from host by adding weavedns ip (docker0 ip) to /etc/resolv.conf. This seems to create circular dependency inside weavedns because it sees docker0 ip as an upstream server.

### PR DESCRIPTION
**Pull request by tomwilkie**
Flag is called ```--dns-effective-listen-address```, and is automatically populated by the ```weave``` script.

Fixes #1343 

Note we don't actually validate the contents of this field (ie check its a real IP address).  We can do, but I didn't see the point.

### CODE REVIEW

File: weave [hunk 1]
```diff
@@ -1162,7 +1162,7 @@ launch_router() {
         -v /var/run/docker.sock:/var/run/docker.sock \
         -e WEAVE_PASSWORD \
         -e WEAVE_CIDR=none \
-        $WEAVE_DOCKER_ARGS $IMAGE $COVERAGE_ARGS --iface $CONTAINER_IFNAME --port $CONTAINER_PORT --name "$PEERNAME" --nickname "$(hostname)" --ipalloc-range "$IPRANGE" "$@")
+        $WEAVE_DOCKER_ARGS $IMAGE $COVERAGE_ARGS --iface $CONTAINER_IFNAME --port $CONTAINER_PORT --name "$PEERNAME" --nickname "$(hostname)" --ipalloc-range "$IPRANGE" --dns-effective-listen-address "$DOCKER_BRIDGE_IP" "$@")
```
Comment (bboreham) [inline weave]: Maybe this could go into `$DNS_PORT_MAPPING`, to keep like things together and so it will be blanked on `--no-dns`?

Comment (tomwilkie) [inline weave]: Good idea.

Comment (tomwilkie) [inline weave]: Actually DNS_PORT_MAPPING are args for docker, these are args for the router itself.

Is it important to blank it when --no-dns?

Comment (bboreham) [inline weave]: Ah.  I don't imagine it would be important to blank it; just that it will show up in logs for people who add `--no-dns`.

File: nameserver/dns.go [hunk 2]
```diff
@@ -52,6 +62,9 @@ func NewDNSServer(ns *Nameserver, domain string, address string, ttl uint32, cli
 	if s.upstream, err = dns.ClientConfigFromFile(etcResolvConf); err != nil {
 		return nil, err
 	}
+	if s.upstream != nil {
```
Comment (inercia) [inline nameserver/dns.go]: Maybe `if s.upstream != nil && len(effectiveAddress) > 0`, for saving some cycles...

**Comment by inercia** [comment]
LGTM.
