### PR TITLE
[proxy] Handle case where no command is specified.

### LINKED ISSUE #1241: proxy swallows error message when container fails to start
````
$ docker run --rm -it gliderlabs/alpine
Error response from daemon: No command specified
$ weave launch
$ eval $(weave env)
$ docker run --rm -it gliderlabs/alpine
Error response from daemon: ba8ea356fa43646ec9e758af06d4443695483f27152c6ff40ca192ce188a5c01 container is not running.
$ docker logs weaveproxy
...
WARN: 2015/07/30 09:54:09.488245 Attaching container ba8ea356fa43646ec9e758af06d4443695483f27152c6ff40ca192ce188a5c01 to weave network failed: ba8ea356fa43646ec9e758af06d4443695483f27152c6ff40ca192ce188a5c01 container is not running.

WARN: 2015/07/30 09:54:09.488313 Error intercepting response: ba8ea356fa43646ec9e758af06d4443695483f27152c6ff40ca192ce188a5c01 container is not running.
````

### PR DESCRIPTION
**Pull request by paulbellamy**
The docker daemon can't do this because we set /w/w.

Fixes #1241

### CODE REVIEW

**Comment by tomwilkie** [comment]
Without the proxy:
```
vagrant@ubuntu-14:~/src/github.com/weaveworks/weave$ docker run gliderlabs/alpine foo
exec: "foo": executable file not found in $PATH
Error response from daemon: Cannot start container ff2e425302332ded5ec18e41cd2f2662d22b3b852ebee078b9e074fd172180b1: [8] System error: exec: "foo": executable file not found in $PATH
vagrant@ubuntu-14:~/src/github.com/weaveworks/weave$ echo $?
1
```

With the proxy:
```
vagrant@ubuntu-14:~/src/github.com/weaveworks/weave$ docker logs hopeful_mayer 
exec: "foo": executable file not found in $PATH
vagrant@ubuntu-14:~/src/github.com/weaveworks/weave$ echo $?
1
```

Not identical, but I don't think there is anything we can do about that.

File: proxy/create_container_interceptor.go [hunk 1]
```diff
@@ -105,7 +110,17 @@ func (i *createContainerInterceptor) setWeaveWaitEntrypoint(container *docker.Co
 		}
```
Comment (tomwilkie) [inline proxy/create_container_interceptor.go]: How can container.Entrypoint ever be nil?  Its zero-value is an empty list, no?  Or is == nil that same as len(...) == 0?  In which case, we already checked that.

File: proxy/create_container_interceptor.go [hunk 2]
```diff
@@ -105,7 +110,17 @@ func (i *createContainerInterceptor) setWeaveWaitEntrypoint(container *docker.Co
...
 	}
 
+	for _, e := range container.Entrypoint {
+		if e != weaveWaitEntrypoint[0] {
+			return nil
+		}
+	}
```
Comment (tomwilkie) [inline proxy/create_container_interceptor.go]: What is this trying to achieve?  Why is it checking all entries in container.Entrypoint?

**Comment by tomwilkie** [comment]
The 620_proxy_entrypoint_command_test.sh failures don't looks intermittent, so it looks like something is really broken there.

File: proxy/create_container_interceptor.go (hunk 1 above)
Comment (paulbellamy) [inline proxy/create_container_interceptor.go]: The difference between it not being present in the JSON, and it being an empty list in the JSON.

```Go
	var a []string
	var b = []string{}
	fmt.Println(a == nil) // true
	fmt.Println(b == nil) // false
```

File: proxy/create_container_interceptor.go (hunk 2 above)
Comment (rade) [inline proxy/create_container_interceptor.go]: This looks just wrong to me. It will return, and hence not insert the `/w/w` when it finds something *other* than `/w/w`.

**Comment by paulbellamy** [comment]
Yeah, not identical. I've had a read through the daemon/client code, but can't quite see why. Can keep digging if we think it's important.

File: proxy/create_container_interceptor.go (hunk 1 above)
Comment (tomwilkie) [inline proxy/create_container_interceptor.go]: You are right, this is a stoopid language.

**Comment by tomwilkie** [comment]
LGTM (not merging as its assigned to you)
