### PR TITLE
[proxy] rewrote chunked response handler

### LINKED ISSUE #1103: Weave proxy unexpectedly closes the connection in chunked responses
In an ECS-optimized AMI in Amazon's EC2, `amazon-ecs-init prestart` fails when using the weave proxy (`DOCKER_HOST=unix:///vart/run/weave.sock`):

```
[root@ip-XXX-XX-XX-XX ec2-user]# DOCKER_HOST=unix:///var/run/weave.sock /usr/libexec/amazon-ecs-init pre-start
2015-07-08T16:25:11Z [INFO] pre-start
2015-07-08T16:25:11Z [ERROR] could not check if Agent is loaded: persistent connection closed
```

However, it works just fine when using Docker directly. 

After further inspection it seems like weave proxy is sending a `Connection: close` header.

Using Weave Proxy:

```
GET /v1.15/images/json?all=1 HTTP/1.1
Host:
User-Agent: go-dockerclient

HTTP/1.1 200 OK
Connection: close
Content-Type: application/json
Date: Wed, 08 Jul 2015 16:07:12 GMT
Transfer-Encoding: chunked
```

Using Docker directly:

```
GET /v1.15/images/json?all=1 HTTP/1.1
Host:
User-Agent: go-dockerclient

HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 08 Jul 2015 16:09:01 GMT
Transfer-Encoding: chunked
```

In case it helps, here's what seems to be the code making the  `/v1.15/images/json?all=1`  request: https://github.com/aws/amazon-ecs-init/blob/master/ecs-init/docker/docker.go#L53

### PR DESCRIPTION
**Pull request by paulbellamy**
1) We cannot send "Connection: close", because the fsouza docker client
expects the tcp socket to stay open between requests.

2) Because we cannot force-close the connection, we can't hijack the
connection (because go's net/http doesn't let use un-hijack it).

3) Because we need to maintain the individual chunking of messages (for
docker-py), we can't just copy the response body, as Go will remove and
re-add the chunking willy-nilly.

Therefore, we have to read each chunk one-by-one, and flush the
ResponseWriter after each one.

Fixes #1103

Merging into master instead of 1.0, as it is definitely not a "patch" change. Replacing #1110.

### CODE REVIEW

File: proxy/proxy_intercept.go [hunk 1]
```diff
@@ -117,29 +116,29 @@ func copyStream(dst io.Writer, src io.Reader, done chan struct{}) {
...
+	var err error
+	chunks := NewChunkedReader(io.MultiReader(rem, up))
+	for chunks.Next() && err == nil {
+		_, err = io.Copy(w, chunks.Chunk())
+		wf.Flush()
+	}
+	if err == nil {
+		err = chunks.Err()
+	}
+	if err != nil {
```
Comment (tomwilkie) [inline proxy/proxy_intercept.go]: Else?

Comment (rade) [inline proxy/proxy_intercept.go]: that would behave differently.

Comment (tomwilkie) [inline proxy/proxy_intercept.go]: Ah yes sorry.

File: proxy/proxy_intercept.go [hunk 2]
```diff
@@ -117,29 +116,29 @@ func copyStream(dst io.Writer, src io.Reader, done chan struct{}) {
...
-	// stopping at the end of the chunked section.
-	rawResponseBody := io.MultiReader(rem, up)
-	if _, err := io.Copy(ioutil.Discard, httputil.NewChunkedReader(io.TeeReader(rawResponseBody, down))); err != nil {
-		http.Error(w, "Error copying chunked response body", http.StatusInternalServerError)
-		return
+
+	var err error
+	chunks := NewChunkedReader(io.MultiReader(rem, up))
+	for chunks.Next() && err == nil {
+		_, err = io.Copy(w, chunks.Chunk())
```
Comment (peterbourgon) [inline proxy/proxy_intercept.go]: Probably better to `io.Copy` into the `wf` for consistency's sake.

File: proxy/proxy_intercept.go [hunk 3]
```diff
@@ -117,29 +116,29 @@ func copyStream(dst io.Writer, src io.Reader, done chan struct{}) {
...
-		http.Error(w, "Unable to hijack response stream for chunked response", http.StatusInternalServerError)
+	wf, ok := w.(http.Flusher)
+	if !ok {
+		http.Error(w, "Error forwarding chunked response body: flush not available", http.StatusInternalServerError)
 		return
 	}
+
+	w.WriteHeader(resp.StatusCode)
+
+	up, rem := client.Hijack()
```
Comment (peterbourgon) [inline proxy/proxy_intercept.go]: I guess `rem` here means.. remaining?

File: proxy/chunked_test.go [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+		e := "malformed chunked encoding"
+		if r.Err() == nil || r.Err().Error() != e {
+			t.Errorf("chunk reader errored %q; want %q", r.Err(), e)
+		}
+		data, err := ioutil.ReadAll(r.Chunk())
+		if len(data) != 0 {
+			t.Errorf("chunk should have been empty. got %q", string(data))
+		}
+		if err != nil {
+			t.Logf(`data: "%s"`, data)
```
Comment (peterbourgon) [inline proxy/chunked_test.go]:
```go
t.Logf("data: %q", data)
```

File: proxy/chunked_test.go [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+		if r.Next() {
+			t.Errorf("Expected failure when reading chunks, but got one")
+		}
+		e := "malformed chunked encoding"
+		if r.Err() == nil || r.Err().Error() != e {
+			t.Errorf("chunk reader errored %q; want %q", r.Err(), e)
+		}
+		data, err := ioutil.ReadAll(r.Chunk())
+		if len(data) != 0 {
+			t.Errorf("chunk should have been empty. got %q", string(data))
```
Comment (peterbourgon) [inline proxy/chunked_test.go]: I don't think you need the `string(...)` here?

File: proxy/chunked.go [hunk 6]
```diff
@@ -0,0 +1,146 @@
...
+			err = io.ErrUnexpectedEOF
+		} else if err == bufio.ErrBufferFull {
+			err = ErrLineTooLong
+		}
+		return nil, err
+	}
+	if len(p) >= maxLineLength {
+		return nil, ErrLineTooLong
+	}
+	return trimTrailingWhitespace(p), nil
```
Comment (peterbourgon) [inline proxy/chunked.go]: A reason you don't use one of these options?

```go
strings.TrimSpace(p)
strings.TrimRight(p, " \n\t\r")
```

**Comment by squaremo** [comment]
To check my understanding of what's changed: we no longer hijack the downstream connection to the client, just the upstream connection to docker. Docker is fine with the connection being closed arbitrarily (or we are assuming that); some clients are not.

Is there a reason we have to parse the hijacked upstream, rather than using ChunkedReader as before?

> 1) We cannot send "Connection: close", because the fsouza docker client
> expects the tcp socket to stay open between requests.

Just to be clear, this is a bug in that client, right? It should deal with the HTTP connection being closed arbitrarily.

**Comment by paulbellamy** [comment]
> Docker is fine with the connection being closed arbitrarily (or we are assuming that); some clients are not.

Yes

> Is there a reason we have to parse the hijacked upstream, rather than using ChunkedReader as before?

ChunkedReader does not expose individual chunks. It just smashes them together into a bytestream. The downstream client (docker-py in particular) expects json objects and http chunks to align.

> Just to be clear, this is a bug in that client, right? It should deal with the HTTP connection being closed arbitrarily.

Yes

**Comment by squaremo** [comment]
> Is there a reason we have to parse the hijacked upstream, rather than using ChunkedReader as before?
> 
> ChunkedReader does not expose individual chunks. It just smashes them together into a bytestream. The downstream client (docker-py in particular) expects json objects and http chunks to align.

Ahh I beg your pardon, I had it the wrong way around. The ChunkedReader was to gate the straight-through byte copy wasn't it.

**Comment by paulbellamy** [comment]
`net/http/httputil.ChunkedReader` just smashes all the bytes together, yes. Our scanner lets us flush after each chunk.
