### PR TITLE
Simplify checks for plugin running

### LINKED ISSUE #2709: weave can transparently fail if weave-kube is running
#### Steps to reproduce:

* Install `weave`.
* Install K8S and `weave-kube`, **keep `kubelet` running**.
* Run test `130_expose_test.sh`.

#### Symptoms:

* `weave launch --ipalloc-range $UNIVERSE` appears to succeed (it returns `0`), but 
* the `weave` container actually fails to start with (see `docker logs weave`):

```
INFO: 2016/12/21 14:22:39.240455 Command line options: map[[...] ipalloc-range:10.2.3.0/24]
[...]
FATA: 2016/12/21 14:26:04.601824 listen udp4 :6783: bind: address already in use
[...]
```

* test continues to run as if nothing happened, but containers get allocated to the default IP range (`IPRANGE="10.32.0.0/12"`) instead of the desired one (`10.2.3.0/24`), hence the test eventually fails at later stages.

#### Root cause:

Weave currently checks that containers, including the `weave` container, are running using:

```
wait_for_status() {
    container="$1"
    shift
    while true ; do
        "$@" GET /status >/dev/null 2>&1 && return 0           # check #1
        if ! check_running $container >/dev/null 2>&1 ; then   # check #2
            kill_container $container # stop it restarting
            echo $(death_msg $container) >&2
            return 1
        fi
        fractional_sleep 0.1
    done
}
```

In this case, given `weave-kube` is running and listens on port `6784`, `check #1` passes, even though `check #2` would have failed, and `wait_for_status` therefore returns `0`, and the `weave` script therefore believes the container started successfully and continues happily.

#### Potential resolution:

1. Swap `check #1` and `check #2`, which would have allowed the detection of the issue.
2. Identify whether `weave-kube` is running and maybe print a warning?
  K8S somewhat obfuscates container `Names`, but `weave-net` still appears, e.g.:

```
$ docker ps --format "{{.ID}} {{.Image}} {{.Names}}" | grep weave
b39c42a0fe42 weaveworks/plugin:latest weaveplugin
37204e3958a1 weaveworks/weaveexec:latest weaveproxy
84ce83fc34e0 weaveworks/weave:latest weave
7dd83142ac2d weaveworks/weave-kube:1.8.2 k8s_weave.6e1bac7e_weave-net-xhhpw_kube-system_73b14172-c795-11e6-835d-42010a800002_70eb395b
0b3c68800d04 weaveworks/weave-npc:1.8.2 k8s_weave-npc.83aa94cd_weave-net-xhhpw_kube-system_73b14172-c795-11e6-835d-42010a800002_a831cef3
e15c0bb4381c gcr.io/google_containers/pause-amd64:3.0 k8s_POD.d8dbe16c_weave-net-xhhpw_kube-system_73b14172-c795-11e6-835d-42010a800002_d09c50c8
```

### LINKED ISSUE #2956: is_plugin_v1_enabled is bugged
It is used in two places: before removing the default network `weave` in `stop` and `reset` and before removing left-over plugin sockets in `launch` and `reset`.  In both cases we want to know whether the plugin is _running_.

It works by checking the arguments for `--plugin`.  This misses the case `--plugin=false` which would disable it. And it does not check if the container with that argument is running.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2956 
Fixes #2709

1. `weave status` now does plugin-v1 and plugin-v2 in Go code.
2. all other uses of `is_plugin_vX_enabled`collapse to "is weaver running?"
2a. in `stop` before calling `remove-plugin-network`, if plugin was disabled then `RemoveNetwork` will return `NoSuchNetwork`
2b. in `protect_against_docker_hang` if weaver is not running it's ok to remove the plugin sockets.
2c. in `launch` we now error if weaver is already running for any reason

### CODE REVIEW

File: plugin/plugin.go [hunk 1]
```diff
@@ -57,8 +57,7 @@ func run(dockerClient *docker.Client, weave *weaveapi.Client, address, meshAddre
 	if !isPluginV2 {
 		Log.Println("Creating default 'weave' network")
 		options := map[string]interface{}{MulticastOption: "true"}
-		// TODO: the driver name should be extracted from pluginMeshSocket
-		dockerClient.EnsureNetwork("weave", "weavemesh", defaultSubnet, options)
+		dockerClient.EnsureNetwork("weave", pluginNameFromAddress(meshAddress), defaultSubnet, options)
```
Comment (marccarre) [inline plugin/plugin.go]: Minor/Nitpick: replace `"weave"` with a constant.

File: plugin/status.go [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+	DriverName     string
+	MeshDriverName string `json:"MeshDriverName,omitempty"`
+	Version        int
+}
+
+func NewStatus(address, meshAddress string, isPluginV2 bool) *Status {
+	status := &Status{
+		DriverName:     pluginNameFromAddress(address),
+		MeshDriverName: pluginNameFromAddress(meshAddress),
+		Version:        1,
```
Comment (marccarre) [inline plugin/status.go]: Minor/Nitpick: replace `1` with a constant, esp. as used in `prog/weaver/http.go` in `{{if eq .Plugin.Version 1}}`

File: plugin/status.go [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+	}
+	if isPluginV2 {
+		status.Version = 2
```
Comment (marccarre) [inline plugin/status.go]: Minor/Nitpick: replace `2` with a constant.

File: prog/weaver/http.go [hunk 4]
```diff
@@ -203,6 +205,18 @@ var statusTemplate = defTemplate("status", `\
...
 {{end}}\
+{{if .Proxy}}\
+
+        Service: proxy
+        Address: {{printList .Proxy.Addresses}}
+{{end}}\
+{{if .Plugin}}\
+
+        Service: plugin (v{{.Plugin.Version}})
+{{if eq .Plugin.Version 1}}\
```
Comment (marccarre) [inline prog/weaver/http.go]: Minor/Nitpick: replace `1` with a constant, esp. as used in `plugin/status.go` in `Version:        1,`

File: plugin/plugin.go (hunk 1 above)
Comment (brb) [inline plugin/plugin.go]: Not related to your PR, but this should be moved to the `if meshAddress != '' {` branch.

File: prog/weaver/main.go [hunk 5]
```diff
@@ -427,6 +427,12 @@ func main() {
 	}
 	checkFatal(router.CreateRestartSentinel())
 
+	// Slightly ugly that plugin status is separated from the plugin.Start call
```
Comment (brb) [inline prog/weaver/main.go]: I'd suggest to slightly refactor the plugin package:

* Introduce the `func NewPlugin(...) *Plugin` function.
* Create the `func (p *Plugin) Start()` method.
* Create the `func (p *Plugin) Status() Status` method.

The change would allow us to pass the `*Plugin` instance instead of  `pluginStatus`.

File: plugin/status.go (hunk 2 above)
Comment (bboreham) [inline plugin/status.go]: What were you thinking this constant should be called?

File: plugin/plugin.go (hunk 1 above)
Comment (bboreham) [inline plugin/plugin.go]: fixed both; good spot @brb

File: plugin/status.go (hunk 2 above)
Comment (marccarre) [inline plugin/status.go]: No strong opinion but maybe:
- `const PluginV1 = 1`?
- `const PluginV2 = 2`?

given we have `isPluginV2`.

Comment (bboreham) [inline plugin/status.go]: Fixed a different way

File: prog/weaver/main.go (hunk 5 above)
Comment (bboreham) [inline prog/weaver/main.go]: I did this refactoring.

File: prog/weaver/http.go [hunk 6]
```diff
@@ -203,6 +205,20 @@ var statusTemplate = defTemplate("status", `\
...
+
+        Service: proxy
+        Address: {{printList .Proxy.Addresses}}
+{{end}}\
+{{if .Plugin}}\
+
+{{if .Plugin.Config.EnableV2}}\
+        Service: plugin (v2)
+{{else}}\
+        Service: plugin (v1)
```
Comment (brb) [inline prog/weaver/http.go]: Shall we rename it to `plugin (legacy)`?

**Comment by brb** [comment]
LGTM besides one nit and you probably don't want to commit the `prog/weaver/weaveutil` executable.

**Comment by bboreham** [comment]
nits fixed
