### PR TITLE
Make weaveutil container-addrs observe $PROCFS

### LINKED ISSUE #1965: various `weave --local` functions are broken
$ sudo weave --local ps
    weave:expose 26:09:9e:a0:d6:a5
    no such file or directory

because it is running

    docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/hostproc -e PROCFS=/hostproc --entrypoint=/usr/bin/weaveutil weaveworks/weaveexec:latest container-addrs /proc weave weave:expose f438f9a36b72

because `$PROCFS` is `/proc`, correct for non`--local` case and `--local` with `weaveutil` accessible, but incorrect for `--local` which has to run `weaveutil` via Docker

### PR DESCRIPTION
**Pull request by awh**
Fix #1965.

### CODE REVIEW

File: prog/weaveutil/addrs.go [hunk 1]
```diff
@@ -4,22 +4,27 @@ import (
 	"fmt"
 	"github.com/fsouza/go-dockerclient"
 	"github.com/weaveworks/weave/common"
+	"os"
 )
 
 func containerAddrs(args []string) error {
 	if len(args) < 2 {
-		cmdUsage("container-addrs", "<procPath> <bridgeName> [containerID ...]")
+		cmdUsage("container-addrs", "<bridgeName> [containerID ...]")
```
Comment (rade) [inline prog/weaveutil/addrs.go]: you forgot to update the arg count check accordingly. Will fix.

**Comment by rade** [comment]
did some flyby refactoring here - we were determining procfs in two weaveutil subcommands.
