### PR TITLE
Better deleting of persisted IPAM data 

### LINKED ISSUE #2209: IPAM hangs if persisted data does not match ipalloc-range
To reproduce:

    $ weave reset
    $ weave launch --ipalloc-range 10.2.0.0/16
    $ weave prime
    $ weave stop
    $ weave launch --ipalloc-range 10.32.0.0/16
    $ weave run -ti alpine /bin/sh

It hangs because `Ring.ChoosePeersToAskForSpace()` returns nothing, so `allocate.Try()` does nothing; there is not even a diagnostic in the logs at debug level.

`weave status` says:

         Status: waiting for IP range grant from peers

### LINKED ISSUE #2246: Router throws an assertion failure if it has persisted data and you change the peer name
Repro: extend test 380 with the three lines at the end here:

````
# Launch two disconnected routers
weave_on $HOST1 launch --name ::1 --ipalloc-init seed=::1,::2
weave_on $HOST2 launch --name ::2 --ipalloc-init seed=::1,::2

# Ensure allocations can proceed
assert_raises "timeout 10 cat <( start_container $HOST1 --name c1)"
assert_raises "timeout 10 cat <( start_container $HOST2 --name c2)"

# Connect routers
weave_on $HOST2 connect $HOST1

# Check connectivity
assert_raises "exec_on $HOST1 c1 $PING c2"
assert_raises "exec_on $HOST2 c2 $PING c1"

# Now restart one router with a different peername
weave_on $HOST2 forget $HOST1
weave_on $HOST2 stop
weave_on $HOST2 launch --name ::3
````

Logs:

````
INFO: 2016/05/03 10:18:57.778034 Command line options: map[ipalloc-range:10.32.0.0/12 name:::3 nickname:host2 port:6783 datapath:datapath dns-effective-listen-address:172.17.0.1 dns-listen-address:172.17.0.1:53 http-addr:127.0.0.1:6784]
INFO: 2016/05/03 10:18:57.778816 Communication between peers is unencrypted.
INFO: 2016/05/03 10:18:57.779838 Our name is 00:00:00:00:00:03(host2)
INFO: 2016/05/03 10:18:57.779864 Initial set of peers: []
INFO: 2016/05/03 10:18:57.780664 Docker API on unix:///var/run/docker.sock: &[ApiVersion=1.22 GitCommit=20f81dd GoVersion=go1.5.3 Os=linux Arch=amd64 KernelVersion=4.2.0-34-generic BuildTime=2016-03-10T21:49:11.235199091+00:00 Version=1.10.3]
INFO: 2016/05/03 10:18:57.780845 [allocator 00:00:00:00:00:03] Deleting persisted data for peername 00:00:00:00:00:02
INFO: 2016/05/03 10:18:57.781955 [allocator 00:00:00:00:00:03] Initialising via deferred consensus
INFO: 2016/05/03 10:18:57.782480 Listening for DNS queries on 172.17.0.1
INFO: 2016/05/03 10:18:57.782506 Sniffing traffic on datapath (via ODP)
INFO: 2016/05/03 10:18:57.783665 Listening for HTTP control messages on 127.0.0.1:6784
panic: Assertion failure

goroutine 40 [running]:
github.com/weaveworks/weave/common.Assert(0xc821360000)
	/go/src/github.com/weaveworks/weave/common/utils.go:16 +0x6c
github.com/weaveworks/weave/ipam.(*Allocator).assertInvariants(0xc821360000)
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:853 +0x146
github.com/weaveworks/weave/ipam.(*Allocator).actorLoop(0xc821360000, 0xc82134b3e0, 0xc82134b440)
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:644 +0xed
created by github.com/weaveworks/weave/ipam.(*Allocator).Start
	/go/src/github.com/weaveworks/weave/ipam/allocator.go:124 +0x120
````

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2209 and fixes #2246

Now, we don't use the persisted data if there is no name, if the name doesn't match, if there is no ring, or if the ring doesn't match.

Including new smoke-tests.

### CODE REVIEW

File: ipam/allocator.go [hunk 1]
```diff
@@ -113,7 +113,20 @@ func NewAllocator(config Config) *Allocator {
...
+		}
+	} else {
+		if len(alloc.seed) != 0 {
+			alloc.infof("Initialising with supplied IPAM seed")
+			alloc.createRing(alloc.seed)
+		} else if alloc.paxos.IsElector() {
+			alloc.infof("Initialising via deferred consensus")
+		} else {
+			alloc.infof("Initialising as observer - awaiting IPAM data from another peer")
+		}
```
Comment (rade) [inline ipam/allocator.go]: I know this is from a refactor... but this inner `if` really should be a `switch`.

Comment (bboreham) [inline ipam/allocator.go]: I changed both if-statements into a switch

**Comment by awh** [comment]
Nice!
