### PR TITLE
[proxy] Fix bug in weave env/config when passing multiple -H flags

### LINKED ISSUE #1527: weave launch-proxy with multiple -H causes invalid weave {config, env} output
What I did:

```
weave launch-proxy -H tcp://0.0.0.0:12375 -H unix:///var/run/weave/weave.sock
weave launch-router
weave env
weave config
```

What I expected:

```
export DOCKER_HOST=tcp://127.0.0.1:12375 ORIG_DOCKER_HOST=
-H=tcp://127.0.0.1:12375
```

What I got:

```
export DOCKER_HOST=tcp://127.0.0.1:12375 unix:///var/run/weave/weave.sock ORIG_DOCKER_HOST=
-H=tcp://127.0.0.1:12375 unix:///var/run/weave/weave.sock
```

From current master.

### PR DESCRIPTION
**Pull request by paulbellamy**
The echo in proxy_addr was not preserving newlines, so the multiple
addrs were all getting returned.

Fixes #1527

### CODE REVIEW

File: proxy/proxy.go [hunk 1]
```diff
@@ -215,9 +215,7 @@ func (proxy *Proxy) ListenAndServeStatus(socket string) {
 }
 
 func (proxy *Proxy) StatusHTTP(w http.ResponseWriter, r *http.Request) {
-	for _, addr := range proxy.normalisedAddrs {
-		fmt.Fprintln(w, addr)
-	}
+	fmt.Fprintln(w, proxy.normalisedAddrs[0])
```
Comment (rade) [inline proxy/proxy.go]: doesn't that mean `weave status` will only show the first listening address?

File: test/650_proxy_env_test.sh [hunk 2]
```diff
@@ -2,6 +2,18 @@
...
+CMD="run -e WEAVE_CIDR=10.2.1.4/24 $SMALL_IMAGE $CHECK_ETHWE_UP"
+
+check() {
+  assert_raises "eval '$(weave_on $HOST1 env)' ; docker $CMD"
+  assert_raises "docker $(weave_on $HOST1 config) $CMD"
+
+  # Check we can use the weave script through the proxy
+  assert_raises "eval '$(weave_on $HOST1 env)' ; $WEAVE version"
+  assert_raises "eval '$(weave_on $HOST1 env)' ; $WEAVE ps"
+  assert_raises "eval '$(weave_on $HOST1 env)' ; $WEAVE launch-router"
```
Comment (rade) [inline test/650_proxy_env_test.sh]: I know this was there before, but now we invoke this twice.... wouldn't it suffice to have *one* of these three tests, e.g. just the version test?
