### PR TITLE
Remove 'weave expose' race in CNI plugin

### LINKED ISSUE #2570: weave-kube race at install
We write out the CNI config file then fire up the Weave Net process; this can lead to transient failures like
https://github.com/kubernetes/kops/pull/621#issuecomment-255004068

If we write out the file only after ascertaining the router is working this would improve the user experience.

Only on first install, though.  Should have some "network readiness" handshake with Kubernetes to fix it more generally.

### LINKED ISSUE #2617: iptables: No chain/target/match by that name.
_From @errordeveloper on October 24, 2016 17:25_

I've installed weave-kube on a Kubernetes cluster, after rebooting a node, weave-kube fails to start and logs this:

```
root@kube-node-0:~# docker logs cfecf98444b0                                                              
INFO: 2016/10/24 17:22:36.316253 Command line options: map[ipalloc-range:10.32.0.0/12 name:ca:dd:16:be:df:
42 nickname:kube-node-0 no-dns:true docker-api: datapath:datapath http-addr:127.0.0.1:6784 ipalloc-init:co
nsensus=2 port:6783]                                                                                      
INFO: 2016/10/24 17:22:36.339086 Communication between peers is unencrypted.                              
INFO: 2016/10/24 17:22:36.342394 Our name is ca:dd:16:be:df:42(kube-node-0)                               
INFO: 2016/10/24 17:22:36.342490 Launch detected - using supplied peer list: [163.172.63.141 62.210.116.20
6]                                                                                                        
INFO: 2016/10/24 17:22:36.406053 [allocator ca:dd:16:be:df:42] Initialising with persisted data           
INFO: 2016/10/24 17:22:36.406158 Sniffing traffic on datapath (via ODP)                                   
INFO: 2016/10/24 17:22:36.407127 ->[62.210.116.206:6783] attempting connection                            
INFO: 2016/10/24 17:22:36.407365 ->[163.172.63.141:6783] attempting connection                            
INFO: 2016/10/24 17:22:36.407662 ->[163.172.63.141:57223] connection accepted                             
INFO: 2016/10/24 17:22:36.411021 ->[62.210.116.206:6783|3e:62:bc:39:9d:42(kube-node-1)]: connection ready;
 using protocol version 2                                                                                 
INFO: 2016/10/24 17:22:36.411151 overlay_switch ->[3e:62:bc:39:9d:42(kube-node-1)] using fastdp           
INFO: 2016/10/24 17:22:36.411262 ->[62.210.116.206:6783|3e:62:bc:39:9d:42(kube-node-1)]: connection added 
(new peer)                                                                                                
INFO: 2016/10/24 17:22:36.413027 Listening for HTTP control messages on 127.0.0.1:6784                    
INFO: 2016/10/24 17:22:36.414151 ->[163.172.63.141:6783|ca:dd:16:be:df:42(kube-node-0)]: connection shutti
ng down due to error: cannot connect to ourself                                                           
INFO: 2016/10/24 17:22:36.414268 ->[163.172.63.141:57223|ca:dd:16:be:df:42(kube-node-0)]: connection shutt
ing down due to error: cannot connect to ourself                                                          
INFO: 2016/10/24 17:22:36.912987 ->[62.210.116.206:6783|3e:62:bc:39:9d:42(kube-node-1)]: connection fully 
established                                                                                               
INFO: 2016/10/24 17:22:36.913654 EMSGSIZE on send, expecting PMTU update (IP packet was 60028 bytes, paylo
ad was 60020 bytes)                                                                                       
INFO: 2016/10/24 17:22:36.914948 sleeve ->[62.210.116.206:6783|3e:62:bc:39:9d:42(kube-node-1)]: Effective 
MTU verified at 1438                                                                                      
iptables: No chain/target/match by that name.                                                             
```

_Copied from original issue: weaveworks/weave-kube#42_

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2617 and fixes #2570

### CODE REVIEW

File: net/veth.go [hunk 1]
```diff
@@ -271,3 +271,21 @@ func subnets(addrs []netlink.Addr) map[string]struct{} {
...
+		return err
+	}
+	if err := ipt.AppendUnique("nat", "WEAVE", "-d", cidr, "!", "-s", cidr, "-j", "MASQUERADE"); err != nil {
+		return err
+	}
+	if err := ipt.AppendUnique("nat", "WEAVE", "-s", cidr, "!", "-d", cidr, "-j", "MASQUERADE"); err != nil {
+		return err
+	}
+	return nil
+}
```
Comment (rade) [inline net/veth.go]: Shouldn't we replace the code that does the same thing in the weave script with a weaveutil call to this?

Comment (bboreham) [inline net/veth.go]: Done.  It would be nice to go further and replace `expose_ip` but it's a little more complicated with AWSVPC and WeaveDNS integration.

**Comment by raghu67** [comment]
I am eagerly waiting the #2617 fix. When can I expect an image with the fix to be pushed to Docker Hub? Is it it tied to 1.8.1?

**Comment by awh** [comment]
This needs to rebase on/target `1.8` branch amirite?

**Comment by awh** [comment]
@raghu67 yes, it'll be in the 1.8.1 release. We don't have an ETA on that yet, but it will probably be soon.

**Comment by bboreham** [comment]
Retargeted onto 1.8 branch

File: prog/weaveutil/expose.go [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+import (
+	weavenet "github.com/weaveworks/weave/net"
+)
+
+func exposeNAT(args []string) error {
+	if len(args) < 1 {
+		cmdUsage("expose-nat", "<cidr>...")
+	}
+
+	cidrs, err := parseCIDRs(args[1:])
```
Comment (awh) [inline prog/weaveutil/expose.go]: You don't need the `[1:]` here - the command was already stripped off by weaveutil main
