### PR TITLE
npc: Track ipset entries per user and refcount default-allow ipsets

### LINKED ISSUE #3177: New NetworkPolicy implementation fails if pod updates come out of order
Code added in #3151 bypasses reference-counting on ipset membership.
Thus if we get the following sequence:

```
DEBU: 2017/11/17 16:00:25.485583 EVENT UpdatePod {"metadata":{"name":"users-697cd95b9b-7nqhf","generateName":"users-697cd95b9b-","namespace":"default",...
INFO: 2017/11/17 16:00:25.485636 adding entry 10.32.0.7 to weave-local-pods
INFO: 2017/11/17 16:00:25.486942 adding entry 10.32.0.7 to weave-k?Z;25^M}|1s7P3|H9i;*;MhG
INFO: 2017/11/17 16:00:25.488099 adding entry 10.32.0.7 to weave-E.1.0W^NGSp]0_t5WwH/]gX@L

DEBU: 2017/11/17 16:36:23.486668 EVENT UpdatePod {"metadata":{"name":"users-697cd95b9b-ngww4","generateName":"users-697cd95b9b-","namespace":"default",...
INFO: 2017/11/17 16:36:23.486714 adding entry 10.32.0.7 to weave-local-pods
INFO: 2017/11/17 16:36:23.486729 adding entry 10.32.0.7 to weave-k?Z;25^M}|1s7P3|H9i;*;MhG

DEBU: 2017/11/17 16:36:23.501206 EVENT UpdatePod {"metadata":{"name":"users-697cd95b9b-7nqhf","generateName":"users-697cd95b9b-","namespace":"default",..."state":{"terminated":{"exitCode":0,"reason...
INFO: 2017/11/17 16:36:23.501285 deleting entry 10.32.0.7 from weave-local-pods
INFO: 2017/11/17 16:36:23.501299 deleting entry 10.32.0.7 from weave-E.1.0W^NGSp]0_t5WwH/]gX@L
INFO: 2017/11/17 16:36:23.502343 deleting entry 10.32.0.7 from weave-k?Z;25^M}|1s7P3|H9i;*;MhG
```

traffic is now blocked:

```
WARN: 2017/11/17 16:40:41.430346 TCP connection from 10.32.0.10:50902 to 10.32.0.7:80 blocked by Weave NPC.
WARN: 2017/11/17 16:40:42.430273 TCP connection from 10.32.0.10:50902 to 10.32.0.7:80 blocked by Weave NPC.
WARN: 2017/11/17 16:40:44.434329 TCP connection from 10.32.0.10:50902 to 10.32.0.7:80 blocked by Weave NPC.
```

the ipset in question is this one:
```
-A WEAVE-NPC-DEFAULT -m set --match-set weave-E.1.0W^NGSp]0_t5WwH/]gX@L dst -m comment --comment "DefaultAllow isolation for namespace: default" -j ACCEPT
```

I am unclear why it was thought necessary to bypass reference-counting, which was introduced for precisely this reason.

### PR DESCRIPTION
**Pull request by brb**
There was a bug in handling `default-allow` ipsets - it could not cope with out of order receive of Pod updates. E.g:

1) `AddPod(Pod_A, PodIP_A)`,
2) `AddPod(Pod_B, PodIP_A)`,
3) `DeletePod(Pod_A)`,

would result with `PodIP_A` being removed from `default-allow` ipset, as such ipset entries were not refcounted. Bypassing of refcounting was due to the fact that adding a netpol which dst-selects a Pod which IP addr is in `default-allow` ipset has to remove the IP addr from the ipset regardless of refcount value of the IP addr entry in the ipset. So, refcounting in such case didn't make sense and it was bypassed.

This commit changes the way entries are refcounted in ipsets, and it makes `default-allow` ipset the same citizen as other ipsets, so from now `default-allow` ipset is refcounted.

Fix #3177

### CODE REVIEW

File: npc/ipset/ipset.go [hunk 1]
```diff
@@ -65,65 +77,55 @@ func (i *ipset) Create(ipsetName Name, ipsetType Type) error {
...
-	i.Logger.Printf("adding entry %s to %s", entry, ipsetName)
-	if i.inc(ipsetName, entry) > 1 { // already in the set
+func (i *ipset) AddEntry(user types.UID, ipsetName Name, entry string, comment string) error {
+	i.Logger.Printf("adding entry %s to %s of %s", entry, ipsetName, user)
+
+	if !i.addUser(user, ipsetName, entry) { // already in the set
 		return nil
 	}
+
+	i.Logger.Printf("added entry %s to %s of %s", entry, ipsetName, user)
```
Comment (bboreham) [inline npc/ipset/ipset.go]: do we want both 'adding' and 'added' log lines?

File: npc/ipset/ipset.go [hunk 2]
```diff
@@ -65,65 +77,55 @@ func (i *ipset) Create(ipsetName Name, ipsetType Type) error {
...
-}
 
-// DelEntryIfExists does the same as DelEntry but bypasses the ref counting.
-// Should be used only with "default-allow" ipsets.
-func (i *ipset) DelEntryIfExists(ipsetName Name, entry string) error {
-	if i.count(ipsetName, entry) == 0 {
-		return nil
-	}
-	return i.DelEntry(ipsetName, entry)
+	i.Logger.Printf("deleted entry %s from %s of %s", entry, ipsetName, user)
```
Comment (bboreham) [inline npc/ipset/ipset.go]: do we want both 'deleting' and 'deleted' log lines?

File: npc/ipset/ipset.go (hunk 1 above)
Comment (brb) [reply npc/ipset/ipset.go]: We could skip those, but I just want to be able to know when an entry has been actually added to an ipset. We could remove the statements in the future when we know that there aren't any problems with ipset entries.
