### PR TITLE
Fix CNI plugin calling weaveutil

### LINKED ISSUE #2587: Weave-kube CNI plugin fails with missing weaveutil
Symptom is `nsenter: failed to execute weaveutil: No such file or directory`

Because weave-kube copies the plugin binary and makes no provision for that other file to exist.

### PR DESCRIPTION
**Pull request by bboreham**
By the cunning tactic of embedding the CNI plugin inside `weaveutil`

Note I force all uses of `WithNetNS` in `weaveutil` to exec the current program (as defined by `/proc/self/exe`); this seemed better than having it sometimes exec `weaveutil` and sometimes self.

Fixes #2587

### CODE REVIEW

File: weave [hunk 1]
```diff
@@ -1031,7 +1031,7 @@ docker run --rm $(docker_run_options) --pid=host -i \\
  -e CNI_VERSION -e CNI_COMMAND -e CNI_CONTAINERID -e CNI_NETNS \\
  -e CNI_IFNAME -e CNI_ARGS -e CNI_PATH \\
  -v /etc/cni:/etc/cni -v /opt/cni:/opt/cni \$EXTRA_VOLUMES \\
- $PLUGIN_IMAGE $COVERAGE_ARGS $2
+--entrypoint=/usr/bin/weaveutil $EXEC_IMAGE $2
```
Comment (brb) [inline weave]: Why did `$COVERAGE_ARGS` disappear?

Comment (bboreham) [inline weave]: I thought `weaveutil` is not compiled with code coverage

File: prog/weaveutil/main.go [hunk 2]
```diff
@@ -28,10 +31,24 @@ func init() {
 		"del-iface":              delIface,
 		"setup-iface":            setupIface,
 		"list-netdevs":           listNetDevs,
+		"cni-net":                cniNet,
+		"cni-ipam":               cniIPAM,
 	}
 }
 
 func main() {
+	weavenet.WeaveUtilCmd = "/proc/self/exe" // force re-exec of this binary
```
Comment (brb) [inline prog/weaveutil/main.go]: This trick does not work because `WithNetNS` called inside `weaveutil` will exec `nsenter --net=<..> /proc/self/exe <..>`, where `/proc/self/exe` links to `nsenter`.

Comment (bboreham) [inline prog/weaveutil/main.go]: `filepath.EvalSymlinks()` to the rescue!

**Comment by brb** [comment]
LGTM. Waiting for approval from @awh

File: prog/weave-kube/Dockerfile.template [hunk 3]
```diff
@@ -1,3 +1,3 @@
-FROM DOCKERHUB_USER/plugin
+FROM DOCKERHUB_USER/weave
```
Comment (awh) [inline prog/weave-kube/Dockerfile.template]: The Makefile needs to be updated to reflect this dependency change

Comment (bboreham) [inline prog/weave-kube/Dockerfile.template]: done
