### PR TITLE
Fix "weave ps"

### LINKED ISSUE #2388: 'weave ps' fails with "Cannot find weave bridge: Link not found"
... even if the weave bridge exists:

```
weave     Link encap:Ethernet  HWaddr 06:c2:01:12:41:d5  
          inet addr:10.32.0.1  Bcast:0.0.0.0  Mask:255.240.0.0
          inet6 addr: fe80::4c2:1ff:fe12:41d5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1410  Metric:1
          RX packets:732925 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1016150 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:597366797 (597.3 MB)  TX bytes:2877166348 (2.8 GB)
```

This happened when running a local instance of the scope service (kubernetes anywhere). 

Running with `bash -x` I get:

```
+ docker run --rm --privileged --net=host -v /var/run/docker.sock:/var/run/docker.sock --pid=host -e DOCKERHUB_USER=weaveworks -e WEAVE_VERSION -e WEAVE_DEBUG -e WEAVE_DOCKER_ARGS -e WEAVEPROXY_DOCKER_ARGS -e WEAVEPLUGIN_DOCKER_ARGS -e WEAVE_PASSWORD -e WEAVE_PORT -e WEAVE_HTTP_ADDR -e WEAVE_CONTAINER_NAME -e WEAVE_MTU -e WEAVE_NO_FASTDP -e WEAVE_NO_BRIDGED_FASTDP -e WEAVE_NO_PLUGIN -e DOCKER_BRIDGE -e DOCKER_CLIENT_HOST= -e DOCKER_CLIENT_ARGS -e PROXY_HOST=127.0.0.1 -e COVERAGE -e CHECKPOINT_DISABLE weaveworks/weaveexec:1.5.2 --local ps
Cannot find weave bridge: Link not found
```

Output when running the docker command above with WEAVE_DEBUG=1: https://gist.github.com/2opremio/cfe5c7fa236854e9963dda0f8afc5754

Some details about my system:

```
$ uname -a
Linux vagrant-ubuntu-wily-64 4.2.0-36-generic #42-Ubuntu SMP Thu May 12 22:05:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:40:35 2016
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by brb**
This PR fixes the problem described in #2388. In addition, the PR optimizes the `GetBridgeNetDevs` and `containerAddrs` functions.

Keep in mind, that the fix is specific for this case, because we move all the code depending on a non-host netns to the bottom of `containerAddrs` instead of making `WithNetNS` safe.

To address the safety problem, I've filed https://github.com/weaveworks/weave/issues/2419 .

Fixes #2388.

### CODE REVIEW

File: common/utils.go [hunk 1]
```diff
@@ -133,11 +133,20 @@ func GetWeaveNetDevs(processID int) ([]NetDev, error) {
...
 
-// Get the weave bridge interface
-func GetBridgeNetDev(bridgeName string) ([]NetDev, error) {
-	return FindNetDevs(1, func(link netlink.Link) bool {
-		return link.Attrs().Name == bridgeName
+// Get the weave bridge interface.
+func GetBridgeNetDev(bridgeName string) (NetDev, error) {
+	var netdev NetDev
+
+	err := weavenet.WithNetNSLinkByPid(1, bridgeName, func(link netlink.Link) error {
```
Comment (bboreham) [inline common/utils.go]: I think this code was only requesting the root namespace because it was necessary to pass something into `FindNetDevs`.  I believe all uses of `GetBridgeNetDev` are in a context where we may assume we are in the root namespace, so this isn't necessary.

File: prog/weaveutil/addrs.go [hunk 2]
```diff
@@ -41,7 +41,11 @@ func containerAddrs(args []string) error {
 
 func getNetDevs(bridgeName string, c *docker.Client, containerID string) ([]common.NetDev, error) {
 	if containerID == "weave:expose" {
-		return common.GetBridgeNetDev(bridgeName)
+		if netDev, err := common.GetBridgeNetDev(bridgeName); err != nil {
```
Comment (bboreham) [inline prog/weaveutil/addrs.go]: Maybe just 

    netDev, err := common.GetBridgeNetDev(bridgeName)
    return []common.NetDev{netDev}, err
?

File: prog/weaveutil/main.go [hunk 3]
```diff
@@ -30,6 +30,7 @@ func main() {
 		usage()
 		os.Exit(1)
 	}
+
```
Comment (bboreham) [inline prog/weaveutil/main.go]: hmm

File: common/utils.go [hunk 4]
```diff
@@ -90,29 +90,24 @@ func linkToNetDev(link netlink.Link) (NetDev, error) {
...
-	}
+// ConnectedToBridgePredicate returns a function which is used to query whether
+// a given link is a veth interface which one end is connected to a bridge.
+// The returned function should be called from a container network namespace which
+// the bridge does NOT belong to.
+func ConnectedToBridgePredicate(bridgeName string) (func(link netlink.Link) bool, error) {
+	var br netlink.Link
 
-	weaveBridge, err := netlink.LinkByName("weave")
+	err := weavenet.WithNetNSLinkByPid(1, bridgeName, func(link netlink.Link) error {
```
Comment (bboreham) [inline common/utils.go]: Why did this have to change?

File: common/utils.go [hunk 5]
```diff
@@ -90,29 +90,24 @@ func linkToNetDev(link netlink.Link) (NetDev, error) {
...
+		br = link
+		return nil
+	})
 	if err != nil {
-		return nil, fmt.Errorf("Cannot find weave bridge: %s", err)
+		return nil, err
 	}
-	// Scan devices in root namespace to find those attached to weave bridge
+
```
Comment (bboreham) [inline common/utils.go]: You didn't like this comment?

File: common/utils.go (hunk 1 above)
Comment (bboreham) [inline common/utils.go]: OK, it is necessary if `weave:expose` can come in any position in the list of containers in `weave ps`.

Comment (bboreham) [inline common/utils.go]: You could pull the check for `weave:expose` up into another loop that executed before you started changing namespace, then this wouldn't be necessary.  Maybe that's too obscure.

File: prog/weaveutil/addrs.go [hunk 6]
```diff
@@ -11,47 +13,65 @@ func containerAddrs(args []string) error {
...
-			if _, ok := err.(*docker.NoSuchContainer); ok {
-				continue
+	pred, err := common.ConnectedToBridgePredicate(bridgeName)
+	if err != nil {
+		return err
+	}
+
+	containers := make(map[string]*docker.Container)
+	for _, cid := range containerIDs {
+		if containers[cid], err = client.InspectContainer(cid); err != nil {
```
Comment (bboreham) [inline prog/weaveutil/addrs.go]: We could hoist `weave:expose` handling up to here, then we wouldn't try to `Inspect` it and we wouldn't have to do special pid-1 handling for the weave bridge address.

File: common/utils.go (hunk 5 above)
Comment (brb) [inline common/utils.go]: Forgot to c&p. Thanks for noting.

File: prog/weaveutil/main.go (hunk 3 above)
Comment (brb) [inline prog/weaveutil/main.go]: ouch :(

File: prog/weaveutil/addrs.go (hunk 2 above)
Comment (brb) [inline prog/weaveutil/addrs.go]: I'd be in favour of returning empty list in the case of error.

File: common/utils.go (hunk 4 above)
Comment (brb) [inline common/utils.go]: Good spot. Anyway, I'm wrapping both with `WithNetNS*`, because the `GetWeaveNetDevs`, which calls the predicate function, is used by the proxy and atm `WithNetNS*` is not safe.

File: prog/weaveutil/addrs.go (hunk 6 above)
Comment (brb) [inline prog/weaveutil/addrs.go]: I've considered that, but as you mentioned it makes the first loop a bit obscure. Anyway, changing it for the sake of simplicity.

File: prog/weaveutil/addrs.go [hunk 7]
```diff
@@ -12,46 +14,63 @@ func containerAddrs(args []string) error {
...
 
 	return nil
 }
 
-func getNetDevs(bridgeName string, c *docker.Client, containerID string) ([]common.NetDev, error) {
-	if containerID == "weave:expose" {
-		return common.GetBridgeNetDev(bridgeName)
-	}
-
-	container, err := c.InspectContainer(containerID)
```
Comment (brb) [inline prog/weaveutil/addrs.go]: Ehrm, I've changed the behaviour of `container-addrs`: if a user passes a non-existing container id, we return an error instead of ignoring it. This becomes relevant in racy cases, e.g. container dies immediately after we have invoked `container-addrs`. I'll revert the changes to the behaviour.

Comment (bboreham) [inline prog/weaveutil/addrs.go]: Just to clarify, this comment about "changed the behaviour of `container-addrs`" is now out of date because you reverted the change?

File: common/utils.go [hunk 8]
```diff
@@ -77,21 +77,54 @@ func forEachLink(f func(netlink.Link) error) error {
...
-func GetWeaveNetDevs(processID int) ([]NetDev, error) {
+// ConnectedToBridgePredicate returns a function which is used to query whether
+// a given link is a veth interface which one end is connected to a bridge.
+// The returned function should be called from a container network namespace which
+// the bridge does NOT belong to.
+func ConnectedToBridgePredicate(bridgeName string) (func(link netlink.Link) bool, error) {
+	indexes := make(map[int]struct{})
+
+	// Scan devices in root namespace to find those attached to weave bridge
+	err := weavenet.WithNetNSLinkByPidUnsafe(1, bridgeName,
```
Comment (bboreham) [inline common/utils.go]: If I understand the series of comments, this changed from assuming we are in the root namespace to assuming we might not be, because it is called from the Proxy which also changes to other namespaces.

But, I believe we are changing the proxy to exec another process to change namespace, and once we have that we can revert this change which will simplify the code here and remove the need for `WithNetNSLinkByPidUnsafe()`

**Comment by bboreham** [comment]
LGTM assuming my questions for clarification come out the way I think.

File: prog/weaveutil/addrs.go (hunk 7 above)
Comment (brb) [inline prog/weaveutil/addrs.go]: Yep, I've reverted the change. However, this PR changes the order of inspecting: `foreach container { inspect && print}` -> `foreach container { inspect }; foreach container { print }`, so it extends the "window" for a race when a container dies immediately after the inspect.

File: common/utils.go (hunk 8 above)
Comment (brb) [inline common/utils.go]: Yep, your reasoning is correct - once we have made `WithNetNS*` safe (which happens in #2419), the wrapper becomes redundant.
