### PR TITLE
[proxy] Use USR2 signal to tell weavewait when to continue

### LINKED ISSUE #812: [proxy] intermittent failure in entry point test
I'm seeing the following every now and then...
````
$ ./620_proxy_entrypoint_command_test.sh 
Proxy uses correct entrypoint and command with weavewait
...
test #3 "proxy docker_on 192.168.48.11 run -e 'WEAVE_CIDR=10.2.1.1/24' --entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier" failed:
	program terminated with code 1 instead of 0
````

Running the failing command repeatedly on the host produces a failure about half the time...
````
root@host1:~# docker -H localhost:12375 run -e 'WEAVE_CIDR=10.2.1.1/24' --entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier
1
root@host1:~# docker -H localhost:12375 run -e 'WEAVE_CIDR=10.2.1.1/24' --entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier
1
FATA[0000] Error response from daemon: Container bf6d0a5ae5735d4443613cc165e3e4ac4e62639e720120c98aead839db59092d died 
root@host1:~# docker -H localhost:12375 run -e 'WEAVE_CIDR=10.2.1.1/24' --entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier
1
FATA[0000] Error response from daemon: Container 885c2204b90952cc0274c196b63d5b890cc84750ff0934bf67153280e7a0be3f died 
````
The log of the failed container contains `1`.

### PR DESCRIPTION
**Pull request by paulbellamy**
There was a race condition with containers running and exiting before
`weave attach` was finished, which would cause an error.

Closes #812

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -55,13 +55,15 @@ $(WEAVER_EXE) $(WEAVEDNS_EXE) $(WEAVEPROXY_EXE) $(WEAVEWAIT_EXE): common/*.go co
 $(WEAVER_EXE): router/*.go ipam/*.go ipam/*/*.go prog/weaver/main.go
 $(WEAVEDNS_EXE): nameserver/*.go prog/weavedns/main.go
 $(WEAVEPROXY_EXE): proxy/*.go prog/weaveproxy/main.go
-$(WEAVEWAIT_EXE): prog/weavewait/*.go
 
 # Sigproxy needs separate rule as it fails the netgo check in the main
```
Comment (rade) [inline Makefile]: "sigproxy and weavewait need ...". And stick a blank line after the comment.

File: prog/weavewait/main.go [hunk 2]
```diff
@@ -1,17 +1,25 @@
...
 	"os"
 	"os/exec"
+	"os/signal"
 	"syscall"
-
-	"github.com/weaveworks/weave/net"
+	"time"
 )
 
+var timeoutErr = errors.New("Container timed out waiting for ethwe interface")
```
Comment (rade) [inline prog/weavewait/main.go]: inline that. and make the description accurate. "Container timed out waiting for signal from proxy"?
