### PR TITLE
Fix reclaim after using CNI

### LINKED ISSUE #2548: "Unable to claim" message on re-launching Weave after using CNI
Exhibit A:

```
$ weave launch-router
Unable to claim: address 10.32.0.3/12 is already owned by 09fc04f55c5554153c7c15c7b2c7f35dd0f9230931276f7f158477b8c8070d42
Unable to claim: address 10.32.0.1/12 is already owned by 10763731d3c707577c044256e607a511b103bfdf7f194d0e3ff4e87d1826b10d
a4c28d85c90f6e4cb6903d2d46e670316ef288ad63afb05d18af76ea3a7fd874
```

From WEAVE_DEBUG log:

```
+ read CONTAINER_ID CONTAINER_IFACE CONTAINER_MAC CONTAINER_IPS
+ ipam_reclaim 09fc04f55c5554153c7c15c7b2c7f35dd0f9230931276f7f158477b8c8070d42 eth0 8e:bd:fb:dd:be:a8 10.32.0.3/12
+ CONTAINER_ID=09fc04f55c5554153c7c15c7b2c7f35dd0f9230931276f7f158477b8c8070d42
+ [ eth0 = ethwe ]
+ CONTAINER_ID=_
+ http_call 127.0.0.1:6784 PUT /ip/_/10.32.0.3/12?noErrorOnUnknown=true&?check-alive=true
+ addr=127.0.0.1:6784
+ http_verb=PUT
+ url=/ip/_/10.32.0.3/12?noErrorOnUnknown=true&?check-alive=true
+ shift 3
+ CURL_TMPOUT=/tmp/weave_curl_out_28654
+ curl -o /tmp/weave_curl_out_28654 -w %{http_code} --connect-timeout 3 -s -S -X PUT http://127.0.0.1:6784/ip/_/10.32.0.3/12?noErrorOnUnknown=true&?check-alive=true
+ HTTP_CODE=400
+ [ -f /tmp/weave_curl_out_28654 ]
+ cat /tmp/weave_curl_out_28654
Unable to claim: address 10.32.0.3/12 is already owned by 09fc04f55c5554153c7c15c7b2c7f35dd0f9230931276f7f158477b8c8070d42
```

so the code sees the interface is `eth0` and from there assumes that IPAM would not know the container ID - this is the case when we use the Weave Plugin.  But it does know the ID, because this one was set up via CNI.

This behaviour was introduced by #2262 

Maybe we can interpret `"_"` as "I don't care what ID it is under" ?

### PR DESCRIPTION
**Pull request by marccarre**
Fixes #2548.

### CODE REVIEW

**Comment by marccarre** [comment]
Trying to reproduce the bug again after the fix, I get:

```
DEBU: 2016/11/01 16:41:35.779545 [http] PUT /ip/weave:expose/10.32.0.2/12?noErrorOnUnknown=true
DEBU: 2016/11/01 16:41:35.779730 [allocator b6:98:38:eb:2d:20]: Re-claimed 10.32.0.2/12 for weave:expose
DEBU: 2016/11/01 16:41:35.822143 [http] PUT /ip/_/10.32.0.3/12?noErrorOnUnknown=true&?check-alive=true
DEBU: 2016/11/01 16:41:35.823087 [allocator b6:98:38:eb:2d:20]: Re-claimed 10.32.0.3/12 for ID _ having existing ID as 0ac4ecaca83690669e0c23c38a0283090c67d56378882f198381144291432374
DEBU: 2016/11/01 16:41:35.835600 [http] PUT /ip/_/10.32.0.1/12?noErrorOnUnknown=true&?check-alive=true
DEBU: 2016/11/01 16:41:35.835726 [allocator b6:98:38:eb:2d:20]: Re-claimed 10.32.0.1/12 for ID _ having existing ID as bfb37e0c0fbae20c61f8d1008c8aaa4222265fd2e3dd874a5e9cdbb02d00bc22
```

and no more `"Unable to claim"` error.

**Comment by marccarre** [comment]
One smoke test failed:
```
vagrant@vagrant-ubuntu-wily-64:~/weave/test$ ./820_plugin_subnet_test.sh 
Test Docker Network plugin with specified subnet
[...]
test #2 "container_ip 192.168.48.11 c2" failed:
	expected "10.40.0.2"
	got "10.40.0.1"
1 of 4 tests failed in 4.345s.
```

**Comment by marccarre** [comment]
Looking better after the latest change:

```
$ ./820_plugin_subnet_test.sh 
Test Docker Network plugin with specified subnet
[...]
all 4 tests passed in 4.369s.
```

```
$ ./830_cni_plugin_test.sh
Test CNI plugin
[...]
all 3 tests passed in 5.201s.
```

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
03bd177e66ca        alpine              "/bin/sh"           29 seconds ago      Up 28 seconds                           c3
68e5d475d740        alpine              "/bin/sh"           31 seconds ago      Up 30 seconds                           c1
```

```
$ weave launch-router --log-level=debug
a9f87412e7c24148e2d3e912a42ff4146ad91051bdadea14b98dea1ab0579b64
```

```
$ docker logs weave
[...]
DEBU: 2016/11/02 11:29:43.165182 [http] GET /status
DEBU: 2016/11/02 11:29:43.179389 [http] PUT /ip/weave:expose/10.32.0.2/12?noErrorOnUnknown=true
DEBU: 2016/11/02 11:29:43.179602 [allocator 52:d4:f5:fe:f1:85]: Re-claimed 10.32.0.2/12 for weave:expose
DEBU: 2016/11/02 11:29:43.202197 [http] PUT /ip/_/10.32.0.3/12?noErrorOnUnknown=true&?check-alive=true
DEBU: 2016/11/02 11:29:43.202438 [allocator 52:d4:f5:fe:f1:85]: Re-claimed 10.32.0.3/12 for ID _ having existing ID as 03bd177e66ca447fe21a492d1c92dd68d45aa77b1e5c5361397b000297d44d56
DEBU: 2016/11/02 11:29:43.206997 [http] PUT /ip/_/10.32.0.1/12?noErrorOnUnknown=true&?check-alive=true
DEBU: 2016/11/02 11:29:43.207150 [allocator 52:d4:f5:fe:f1:85]: Re-claimed 10.32.0.1/12 for ID _ having existing ID as 68e5d475d7404b3ea0c5008e7e32452fcf5c0dc28e5ccb6d1bce398076e26531
```

```
$ curl -X GET 127.0.0.1:6784/ip/03bd177e66ca447fe21a492d1c92dd68d45aa77b1e5c5361397b000297d44d56
10.32.0.3/12
$ curl -X GET 127.0.0.1:6784/ip/68e5d475d7404b3ea0c5008e7e32452fcf5c0dc28e5ccb6d1bce398076e26531
10.32.0.1/12
```

File: test/830_cni_plugin_test.sh [hunk 1]
```diff
@@ -48,12 +48,22 @@ assert_raises "exec_on $HOST1 c2 $PING $C1IP"
 # Now remove and start a new container to see if IP address re-use breaks things
 docker_on $HOST1 rm -f c2
 
-docker_on $HOST1 run --net=none --name=c3 -dt $SMALL_IMAGE /bin/sh
+C3=$(docker_on $HOST1 run --net=none --name=c3 -dt $SMALL_IMAGE /bin/sh)
```
Comment (bboreham) [inline test/830_cni_plugin_test.sh]: why not just refer to it as `c3` ?

File: test/830_cni_plugin_test.sh [hunk 2]
```diff
@@ -48,12 +48,22 @@ assert_raises "exec_on $HOST1 c2 $PING $C1IP"
...
 
+C3IP=$(container_ip $HOST1 c3)
+
 assert_raises "exec_on $HOST1 c1 $PING $C2IP"
 
+
+# Ensure existing containers can reclaim their IP addresses after CNI has been used -- see #2548
+stop_weave_on $HOST1
+weave_on $HOST1 launch-router
+assert "container_ip $HOST1 $C1" "$C1IP"
```
Comment (bboreham) [inline test/830_cni_plugin_test.sh]: This isn't testing the right thing; `container_ip` essentially looks at the veth to see what IP address is attached, while the thing we are interested in is what IPAM has stored internally.

Also the original complaint was spurious messages, which are not examined here.

File: weave [hunk 3]
```diff
@@ -1277,10 +1277,16 @@ check_overlap() {
 # with_container_addresses.
 ipam_reclaim() {
     CONTAINER_ID="$1"
-    # The weave IP addresses of containers attached by the plugin are
-    # recorded specially in IPAM, since the container id is not know
-    # at the time.
+
+    # Weave keeps track of which container has which IP in its IPAM.
+    # If the container's network interface is not the same as Weave's
+    # then it is likely the container was not started by Weave.
```
Comment (bboreham) [inline weave]: This isn't quite right; how it's started is orthogonal to how it gets attached to the network.

"if the network interface is not named `ethwe`, then it was attached via Docker Plugin or via CNI"

File: ipam/claim.go [hunk 4]
```diff
@@ -78,28 +78,36 @@ func (c *claim) Try(alloc *Allocator) bool {
...
+	case existingIdent == "":
+		// Unused address, we try to claim it:
 		if err := alloc.space.Claim(c.cidr.Addr); err == nil {
-			alloc.debugln("Claimed", c.cidr, "for", c.ident)
-			alloc.addOwned(c.ident, c.cidr, c.isContainer)
+			ident := c.ident
+			if ident == api.NoContainerID {
+				ident = c.cidr.Addr.String()
+			}
+			alloc.debugln("Claimed", c.cidr, "for", ident)
```
Comment (bboreham) [inline ipam/claim.go]: This one may as well say `c.ident`; it preserves more information.

File: ipam/claim.go [hunk 5]
```diff
@@ -78,28 +78,36 @@ func (c *claim) Try(alloc *Allocator) bool {
...
 			c.sendResult(nil)
 		} else {
 			c.sendResult(err)
 		}
-	case c.ident:
-		// same identifier is claiming same address; that's OK
-		alloc.debugln("Re-Claimed", c.cidr, "for", c.ident)
+	case (existingIdent == c.ident) || (c.ident == api.NoContainerID && existingIdent == c.cidr.Addr.String()):
+		// Same identifier is claiming same address, which is OK:
+		alloc.debugln("Re-claimed", c.cidr, "for", c.ident)
```
Comment (bboreham) [inline ipam/claim.go]: Generally we keep trivial fixes to formatting, spelling, etc., outside of behaviour-changing PRs, so it's easier to review the change that matters.
I would challenge whether these two are necessary at all.

File: test/830_cni_plugin_test.sh (hunk 1 above)
Comment (marccarre) [inline test/830_cni_plugin_test.sh]: True, not useful here, as `weave ps c3` would have been equivalent.
However, it seems I need the full container ID for `curl` commands:

```
$ curl -X GET 127.0.0.1:6784/ip/c3
# No output

$ curl -X GET 127.0.0.1:6784/ip/8d5f808eee90
# No output

$ docker inspect --format="{{.Id}}" c3
8d5f808eee901c6fc5796aa894fb49727a295adf15eca35c4fd6721df19d1f3f

$ curl -X GET 127.0.0.1:6784/ip/8d5f808eee901c6fc5796aa894fb49727a295adf15eca35c4fd6721df19d1f3f
10.32.0.3/12
```

File: test/830_cni_plugin_test.sh (hunk 2 above)
Comment (marccarre) [inline test/830_cni_plugin_test.sh]: * Is there a higher-level API to get access to IPAM's content, or is it best to use the HTTP API with `curl`?
* Fair point about the message, I'll add checks for this.

File: weave (hunk 3 above)
Comment (marccarre) [inline weave]: I misunderstood what you explained then, will revert the comment.

File: ipam/claim.go (hunk 4 above)
Comment (marccarre) [inline ipam/claim.go]: Will change.

File: ipam/claim.go (hunk 5 above)
Comment (marccarre) [inline ipam/claim.go]: Will revert.

File: ipam/claim.go [hunk 6]
```diff
@@ -84,7 +85,7 @@ func (c *claim) Try(alloc *Allocator) bool {
 		// Unused address, we try to claim it:
 		if err := alloc.space.Claim(c.cidr.Addr); err == nil {
 			alloc.debugln("Claimed", c.cidr, "for", c.ident)
-			if c.ident == "_" { // Special "I don't have a unique ID" identifier
+			if c.ident == api.NoContainerID { // Special "I don't have a unique ID" identifier
```
Comment (bboreham) [inline ipam/claim.go]: Don't need the comment now.

File: plugin/ipam/driver.go [hunk 7]
```diff
@@ -72,9 +72,9 @@ func splitPoolID(poolID string) (subnet, iprange *net.IPNet, err error) {
 func (i *Ipam) RequestAddress(poolID string, address net.IP, options map[string]string) (ip *net.IPNet, _ map[string]string, err error) {
 	i.logReq("RequestAddress", poolID, address, options)
 	defer func() { i.logRes("RequestAddress", err, ip) }()
-	// If we pass magic string "_" to weave IPAM it stores the address under its own string
+	// If we pass magic string api.NoContainerID to weave IPAM it stores the address under its own string
```
Comment (bboreham) [inline plugin/ipam/driver.go]: Don't need this comment now.

File: api/ipam.go [hunk 8]
```diff
@@ -5,6 +5,11 @@ import (
 	"net"
 )
 
+// Special "I don't have a unique ID" container identifier, used in various cases:
+// - when the Docker plugin API does not make the container ID available at the point Weave needs it,
+// - when reclaiming an IP for a container using a different network interface.
```
Comment (bboreham) [inline api/ipam.go]: Rather than trying to enumerate the cases, which will be hard to keep up to date, make a more general statement "when the caller does not know the container ID, or is unsure whether IPAM was previously told the ID".

I think the point about the address being filed under its own string, so that needs to be used when deleting, should also be brought out here.

File: test/830_cni_plugin_test.sh [hunk 9]
```diff
@@ -48,12 +48,27 @@ assert_raises "exec_on $HOST1 c2 $PING $C1IP"
...
 
+C3IP=$(container_ip $HOST1 c3)
+
 assert_raises "exec_on $HOST1 c1 $PING $C2IP"
 
+
+# Ensure existing containers can reclaim their IP addresses after CNI has been used -- see #2548
+stop_weave_on $HOST1
+
+ACTUAL_OUTPUT=$(weave_on $HOST1 launch-router 2>&1)
```
Comment (bboreham) [inline test/830_cni_plugin_test.sh]: maybe a comment saying that this part is to detect warning messages

Comment (marccarre) [inline test/830_cni_plugin_test.sh]: Good point -- added in the latest version.

File: ipam/claim.go (hunk 6 above)
Comment (marccarre) [inline ipam/claim.go]: Removed in latest version.
