### PR TITLE
Override stale dns entries received via gossip

### LINKED ISSUE #1867: DNS entries can leak when a peer restarts quickly
When a peer restarts quickly, not all other peers necessarily see the peer go away, since topology gossip data merging may combine the removal and addition, or the events get re-ordered in transit, with the removal being skipped (since it will have an earlier version) - both of these effectively just end up updating the peer UID and version. If that happens on just a single peer then the DNS entries of the restarted peer are all retained. This is problematic in two ways:

- if any containers died on the peer while the weave router was down, their entries are leaked.
- for surviving containers, the version of the re-created entry may well be lower than the existing one, e.g. if previously the entry had been tombstoned and resurrected a few times. If the last version of the entry known by surviving peers was a tombstone, then this will effectively wipe out the re-created entry.

Steps to reproduce
```
host1$ weave launch --no-discovery
host2$ weave launch --no-discovery $HOST1
host3$ weave launch --no-discovery $HOST2

host1$ weave run --name=foo -ti alpine /bin/sh
host3$ weave dns-lookup foo
10.32.0.1

host3$ sudo iptables -A INPUT -s $HOST2 -j DROP
host1$ weave stop; docker rm -f foo; weave launch --no-discovery $HOST3
host3$ sudo iptables -D INPUT -s $HOST2 -j DROP

host3$ weave dns-lookup foo
10.32.0.1
```

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #1867 and #2023.

Also makes the merging of tombstones stable, where everything else is equal.

### CODE REVIEW

File: nameserver/entry.go [hunk 1]
```diff
@@ -105,6 +108,11 @@ func (e1 *Entry) addLowercase() {
 	e1.lHostname = strings.ToLower(e1.Hostname)
 }
 
+func (e *Entry) makeTombstone() {
```
Comment (rade) [inline nameserver/entry.go]: s/makeTombstone/tombstone

File: nameserver/nameserver.go [hunk 2]
```diff
@@ -204,10 +204,30 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
 	}
 
 	n.Lock()
+	isKnownPeer := n.isKnownPeer
+	n.Unlock() // Don't hold the lock over call out to code elsewhere
```
Comment (rade) [inline nameserver/nameserver.go]: why bother locking at all? isKnownPeer doesn't change.

File: nameserver/nameserver.go [hunk 3]
```diff
@@ -204,10 +204,30 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
...
 
+	// Check entries claiming to originate from us against our current data
 	gossip.Entries.filter(func(e *Entry) bool {
-		return n.isKnownPeer(e.Origin)
+		if e.Origin == n.ourName {
+			if ourEntry, ok := n.entries.findEqual(e); ok {
+				if ourEntry.Version < e.Version ||
+					(ourEntry.Version == e.Version && ourEntry.Tombstone != e.Tombstone) {
+					// Take our version of the data, but make the version higher than the incoming
+					ourEntry.Version = e.Version + 1
```
Comment (rade) [inline nameserver/nameserver.go]: modifying ourEntry here means the subsequent merge won't treat the entry as changed, which delays convergence. It's also somewhat dirty.

I suggest copying the entry as is and only increasing the version on the copy.

**Comment by bboreham** [comment]
I have covered all the points raised, but note https://github.com/weaveworks/mesh/issues/28 means the data does not propagate until periodic gossip fires.

File: nameserver/nameserver.go [hunk 4]
```diff
@@ -203,11 +203,30 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
...
+	})
+
 	n.Lock()
 	defer n.Unlock()
 
+	// Check entries claiming to originate from us against our current data
 	gossip.Entries.filter(func(e *Entry) bool {
-		return n.isKnownPeer(e.Origin)
+		if e.Origin == n.ourName {
+			n.infof("Received entry like mine: %v", e)
```
Comment (rade) [inline nameserver/nameserver.go]: you'll either want to take that out or drop the level to 'debug'.

File: nameserver/nameserver.go [hunk 5]
```diff
@@ -203,11 +203,30 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
...
+			if ourEntry, ok := n.entries.findEqual(e); ok {
+				if ourEntry.Version < e.Version ||
+					(ourEntry.Version == e.Version && ourEntry.Tombstone != e.Tombstone) {
+					// Take our version of the data, but make the version higher than the incoming
+					higherVersion := e.Version
+					*e = *ourEntry
+					e.Version = higherVersion + 1
```
Comment (rade) [inline nameserver/nameserver.go]: `e.Version++`?

Comment (bboreham) [inline nameserver/nameserver.go]: No, because we've just copied our old version over it, which is at least one behind.

Comment (rade) [inline nameserver/nameserver.go]: ah, I completely misread what this was doing. maybe, just maybe, doing `higherVersion := e.Version + 1` would be clearer.

File: nameserver/nameserver.go [hunk 6]
```diff
@@ -220,13 +239,15 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
 // merge received data into state and return "everything new I've
 // just learnt", or nil if nothing in the received data was new
 func (n *Nameserver) OnGossip(msg []byte) (mesh.GossipData, error) {
+	n.infof("Received gossip")
```
Comment (rade) [inline nameserver/nameserver.go]: left over debug logging.

File: nameserver/nameserver.go [hunk 7]
```diff
@@ -220,13 +239,15 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
...
 	newEntries, _, err := n.receiveGossip(msg)
 	return newEntries, err
 }
 
 // merge received data into state and return a representation of
 // the received data, for further propagation
-func (n *Nameserver) OnGossipBroadcast(_ mesh.PeerName, msg []byte) (mesh.GossipData, error) {
+func (n *Nameserver) OnGossipBroadcast(s mesh.PeerName, msg []byte) (mesh.GossipData, error) {
+	n.infof("Received gossip broadcast from %s", s)
```
Comment (rade) [inline nameserver/nameserver.go]: left over debug logging.

**Comment by bboreham** [comment]
Updated again, with smoke-test working.  See https://github.com/weaveworks/mesh/pull/29

File: mesh/local_peer.go [hunk 8]
```diff
@@ -149,7 +149,10 @@ func (peer *LocalPeer) handleAddConnection(conn Connection) error {
 	}
 	_, isConnectedPeer := peer.router.Routes.Unicast(toName)
 	peer.addConnection(conn)
-	if isConnectedPeer {
+	if isRestartedPeer {
+		conn.Log("connection added (restarted peer)")
+		peer.router.SendAllGossipDown(conn)
+	} else if isConnectedPeer {
```
Comment (rade) [inline mesh/local_peer.go]: use a `switch`.

Comment (rade) [inline mesh/local_peer.go]: also, you may want to track this as a separate issue, for release notes purposes, since it goes beyond DNS.

File: nameserver/nameserver.go [hunk 9]
```diff
@@ -203,11 +203,29 @@ func (n *Nameserver) receiveGossip(msg []byte) (mesh.GossipData, mesh.GossipData
 		return nil, nil, fmt.Errorf("clock skew of %d detected", delta)
 	}
 
+	gossip.Entries.filter(func(e *Entry) bool {
```
Comment (rade) [inline nameserver/nameserver.go]: deserves a comment as to why we are doing this here rather than as part of the filter below.

File: nameserver/nameserver.go [hunk 10]
```diff
@@ -226,7 +244,7 @@ func (n *Nameserver) OnGossip(msg []byte) (mesh.GossipData, error) {
 
 // merge received data into state and return a representation of
 // the received data, for further propagation
-func (n *Nameserver) OnGossipBroadcast(_ mesh.PeerName, msg []byte) (mesh.GossipData, error) {
+func (n *Nameserver) OnGossipBroadcast(s mesh.PeerName, msg []byte) (mesh.GossipData, error) {
```
Comment (rade) [inline nameserver/nameserver.go]: superfluous change?

File: mesh/local_peer.go (hunk 8 above)
Comment (bboreham) [inline mesh/local_peer.go]: tracked at #2085

**Comment by rade** [comment]
Let's leave out the mesh changes; too dangerous for 1.4.6.

**Comment by bboreham** [comment]
Removed mesh changes, squashed commits
