### PR TITLE
Filter out IPv6 addresses from kube-peers

### LINKED ISSUE #2904: [weave-kube] too many colons in address
Hi there,

I deployed a new kubernetes 1.6.1 cluster via kubeadm this morning, and when applying 
 the https://git.io/weave-kube-1.6 network plugin, I face for the first time the following error:

*weave container*
```
INFO: 2017/04/20 06:29:31.586056 Command line options: map[nickname:kube-master-1 port:6783 conn-limit:30 datapath:datapath http-addr:127.0.0.1:6784 ipalloc-init:consensus=4 docker-api: ipalloc-range:10.32.0.0/12 no-dns:true status-addr:0.0.0.0:6782]
INFO: 2017/04/20 06:29:31.586115 Communication between peers is unencrypted.
INFO: 2017/04/20 06:29:31.607783 Our name is ce:7c:4d:02:b5:73(kube-master-1)
INFO: 2017/04/20 06:29:31.607804 Launch detected - using supplied peer list: [{PUBLIC-IPv4} fe80::250:56ff:fe01:18c0 192.168.0.10 fe80::20c:29ff:fe04:f34d]
INFO: 2017/04/20 06:29:31.607854 Checking for pre-existing addresses on weave bridge
INFO: 2017/04/20 06:29:31.608702 [allocator ce:7c:4d:02:b5:73] Initialising with persisted data
INFO: 2017/04/20 06:29:31.608732 Sniffing traffic on datapath (via ODP)
FATA: 2017/04/20 06:29:31.609096 too many colons in address fe80::250:56ff:fe01:18c0:0
too many colons in address fe80::20c:29ff:fe04:f34d:0
```

I successfully deployed deployed the same cluster yesterday without a problem, on the same machines.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2904

### CODE REVIEW

File: prog/kube-peers/main.go [hunk 1]
```diff
@@ -37,9 +38,9 @@ func getKubePeers() ([]string, error) {
 	for _, peer := range nodeList.Items {
 		var internalIP, externalIP string
 		for _, addr := range peer.Status.Addresses {
-			if addr.Type == "InternalIP" {
+			if addr.Type == "InternalIP" && addressLooksOK(addr.Address) {
```
Comment (brb) [inline prog/kube-peers/main.go]: Maybe better to check whether `addr` is a IPv4?

Comment (bboreham) [inline prog/kube-peers/main.go]: As I say below, there isn't much documentation for what could appear.  Weave will handle a name that resolves to an IPv4 address.  Maybe I'm being over-cautious?

Comment (bboreham) [inline prog/kube-peers/main.go]: I scanned the Kubernetes code to try to find where these addresses come from.  There are various implementations, from AWS, Rackspace, Openstack, etc.  There is no consistency, but they do all seem likely to generate a numeric IP address rather than a name.

**Comment by brb** [comment]
LGTM. Just waiting for tests to finish.
