### PR TITLE
Remove DNS entries for dead containers when adding correctly.

### LINKED ISSUE #1281: weave dns doesn't remove entries for containers that die super young
Which is what you see in weave status and docker ps

```
vagrant@ubuntu-14:~/src/github.com/weaveworks/service$ weave status
weave router git-073836905a97
Our name is aa:4f:5c:2c:f8:7d(ubuntu-14)
Encryption off
Peer discovery on
Sniffing traffic on &{1102 65535 ethwe b2:37:e1:49:ac:c0 up|broadcast|multicast}
MACs:
6a:93:5b:00:1b:ad -> aa:4f:5c:2c:f8:7d(ubuntu-14) (2015-08-11 09:59:44.287784384 +0000 UTC)
d2:63:6d:68:ec:d6 -> aa:4f:5c:2c:f8:7d(ubuntu-14) (2015-08-11 10:06:30.182731544 +0000 UTC)
ee:5c:de:f3:5f:4d -> aa:4f:5c:2c:f8:7d(ubuntu-14) (2015-08-11 10:00:26.234948009 +0000 UTC)
b6:d0:88:77:89:a8 -> aa:4f:5c:2c:f8:7d(ubuntu-14) (2015-08-11 09:59:44.29417889 +0000 UTC)
f6:da:96:f2:e1:6d -> aa:4f:5c:2c:f8:7d(ubuntu-14) (2015-08-11 10:06:30.183672974 +0000 UTC)
Peers:
aa:4f:5c:2c:f8:7d(ubuntu-14) (v0) (UID 29660472120172713)
Routes:
unicast:
aa:4f:5c:2c:f8:7d -> 00:00:00:00:00:00
broadcast:
aa:4f:5c:2c:f8:7d -> []
Direct Peers:
Reconnects:

Allocator range [10.32.0.0-10.48.0.0)
Owned Ranges:
  10.32.0.0 -> aa:4f:5c:2c:f8:7d (ubuntu-14) (v314)
Allocator default subnet: 10.32.0.0/12

WeaveDNS (aa:4f:5c:2c:f8:7d)
  listening on 0.0.0.0:53, for domain weave.local.
  response ttl 1

c26978e5ee4d: scope-app-1.weave.local. [10.32.0.8]
```

```
vagrant@ubuntu-14:~/src/github.com/weaveworks/service$ weave dns-remove 10.32.0.8 c26978e5ee4d 
Error: No such container: c26978e5ee4d
```

### PR DESCRIPTION
**Pull request by tomwilkie**
Fixes #1281

### CODE REVIEW

File: nameserver/http.go [hunk 1]
```diff
@@ -8,13 +8,12 @@ import (
...
 
-	"github.com/weaveworks/weave/common"
 	"github.com/weaveworks/weave/net/address"
 )
 
-func badRequest(w http.ResponseWriter, err error) {
+func (n *Nameserver) badRequest(w http.ResponseWriter, err error) {
 	http.Error(w, err.Error(), http.StatusBadRequest)
-	common.Log.Warningf("[gossipdns]: %v", err)
+	n.infof("[nameserver]: %v", err)
```
Comment (tomwilkie) [inline nameserver/http.go]: drop [nameserver]
