### PR TITLE
resolve inconsistencies detected during ring merge

### LINKED ISSUE #1962: resolve inconsistencies detected during ring merge
The following are resolvable inconsistencies that currently cause a ring merge to fail, which in turn causes the connection on which the "other" ring was transmitted to be dropped...
- we receive an entry that splits one of our ranges, giving some of it away to another peer. This is in fact acceptable provided that we have no allocations in the range that got given away.
- we receive an entry with a token and version identical to an entry we have, but holding different content. We could apply a simple tie-break here, e.g. pick the entry with the highest free count and, if that is the same, lowest peer id. The only time we should error is when this tie-breaking ends up giving away a range we own and which has allocations.
- we receive an entry with a token that is equal to one of the entries we have, and has a newer version, but the entry we hold belongs to us. i.e. we've received an update to one of our own tokens, which shouldn't happen. We can, however, accept the received entry if either it belongs to a different peer and we do not have allocations in the range effectively given away, or it belongs to our own peer, in which case we should set our version to the one received plus one, effectively imposing our existing entry.

The 2nd of these is particularly important to address, at least partially, since it can cause a merge to fail on a peer for entries involving two other peers. Fixing just that would entail applying the tie-break as described and fail if that picks the received entry and the entry we hold belongs to us.

### PR DESCRIPTION
**Pull request by murali-reddy**
implements tie-breaker suggestions in #1962 and unit-tests to test the behaviour

Fixes #1962

### CODE REVIEW

File: ipam/ring/ring.go [hunk 1]
```diff
@@ -292,17 +303,38 @@ func (es entries) merge(other entries, ourPeer mesh.PeerName) (result entries, u
...
 			case mine.Version < theirs.Version:
-				if mine.Peer == ourPeer { // We shouldn't receive updates to our own tokens
-					err = errNewerVersion(mine, theirs)
-					return
+				if mine.Peer == ourPeer {
+					// We received update to our own tokens accept the received entry
+					// if either it belongs to a different peer and we do not have allocations
+					// in the range effectively given away, or it belongs to our own peer
+					if theirs.Peer != ourPeer && !checkEntryHasAllocations(mine, es.entry(i+1)) || theirs.Peer == ourPeer {
+						addTheirs(*theirs)
```
Comment (bboreham) [inline ipam/ring/ring.go]: This is not implementing what it says in #1962 for the latter case:
>  we should set our version to the one received plus one, effectively imposing our existing entry.

Comment (murali-reddy) [reply ipam/ring/ring.go]: I tried the suggestion earlier, but was failing for this case (not sure if this in-valid test scenario)

```
	// we receive an entry that splits one of our ranges, giving some of it
	// away to another peer. accept the entry provided that we have no allocations
	// in the range that got given away.
	ring1 = NewRing(start, end, peer1name)
	ring2 = NewRing(start, end, peer2name)
	ring1.Entries = []*entry{{Token: start, Peer: peer1name, Free: 128, Version: 1}, {Token: middle, Peer: peer2name, Free: 128}}
	ring2.Entries = []*entry{{Token: start, Peer: peer1name, Free: 8, Version: 2}, {Token: dot8, Peer: peer2name, Free: 120, Version: 1}, {Token: middle, Peer: peer2name, Free: 128}}
	require.NoError(t, merge(ring1, ring2))
```

` imposing our existing entry` would mean keeping the free count as it is.

Comment (bboreham) [reply ipam/ring/ring.go]: The `Allocator` calls `reportFreeSpace()` after every action in `actorLoop()`, which should correct the free space.
I can't immediately see why that test case fails.

Comment (bboreham) [reply ipam/ring/ring.go]: After lengthy discussion, I understand the test fails because `Merge()` checks validity of everything before returning.

There is another case where accepting the incoming data is incorrect: if we have allocated some IPs in the free space before the update arrives.

So, I'm thinking that recalculating the free space when accepting an unexpected update is the way to go.

Comment (murali-reddy) [reply ipam/ring/ring.go]: > recalculating the free space when accepting an unexpected update is the way to go
`ring` does not have access to `space` to re-calculate the free space (need invasive changes across allocator, ring, space and tests to accommodate this). Given the conflicting conditions (merging of un-allocated ranges) this PR is addressing, I made change to reset the `Free` to distance between the tokens. PTAL

**Comment by bboreham** [comment]
Appears to be removing the debug logging added in #3627 - is that intended?

File: ipam/ring/ring.go [hunk 2]
```diff
@@ -282,29 +300,57 @@ func (es entries) merge(other entries, ourPeer mesh.PeerName) (result entries, u
 		case mine.Token > theirs.Token:
 			// insert, checking that a range owned by us hasn't been split
 			if previousOwner != nil && *previousOwner == ourPeer && theirs.Peer != ourPeer {
-				err = errEntryInMyRange(theirs)
-				return
+				// check we have no allocations in the range that got split
+				if checkEntryHasAllocations(es.entry(i-1), mine) {
```
Comment (bboreham) [inline ipam/ring/ring.go]: This doesn't seem quite right - suppose the tokens are A ... B ... C, and `theirs.Token` is B.
We want to check if there are allocations in the range B..C, but this code checks A..C.

Comment (murali-reddy) [reply ipam/ring/ring.go]: This is the case of range that got split. Its more like `mine` sees A...C and and `theirs.Token` is B with A<B< C. The check is at the point where `mine.Token` is C and `theirs.Token` is B and `checkEntryHasAllocations(es.entry(i-1), mine)` is checking over range A-C.

**Comment by murali-reddy** [comment]
> Appears to be removing the debug logging added in #3627 - is that intended?

Unintended change due to rebase. Fixed it.

File: ipam/ring/ring.go (hunk 2 above)
Comment (bboreham) [reply ipam/ring/ring.go]: That's what I meant to say - we don't mind if there are allocations in `A..B`, since that's staying with the same ownership; we want to check in `B..C` only since that's the bit that's changing.

Comment (murali-reddy) [reply ipam/ring/ring.go]: got it. Modified the check to only to range `B..C`

File: ipam/ring/ring.go [hunk 3]
```diff
@@ -282,29 +301,57 @@ func (es entries) merge(other entries, ourPeer mesh.PeerName) (result entries, u
 		case mine.Token > theirs.Token:
 			// insert, checking that a range owned by us hasn't been split
 			if previousOwner != nil && *previousOwner == ourPeer && theirs.Peer != ourPeer {
-				err = errEntryInMyRange(theirs)
-				return
+				// check we have no allocations in the range that got split
+				if checkEntryHasAllocations(theirs, mine) {
```
Comment (bboreham) [inline ipam/ring/ring.go]: This checks `theirs.Free < size`, i.e. it is checking if _they_ have any allocations in the range.
I think, to do this correctly, there needs to be some way to check the actual allocations.
Maybe pass in a function that will do that?

Comment (murali-reddy) [reply ipam/ring/ring.go]: Added a function that uses `space` to achieve `checkEntryHasAllocations` for an entry in ring.

**Comment by bboreham** [comment]
Does this fix #2084 ?
