### PR TITLE
Fix bug of --with-ipam not setting entrypoints

### LINKED ISSUE #744: [proxy] entrypoint and dns not configured with `--with-ipam`
Looks like proxy should care about `withIPAM` flag in `proxy/create_container_interceptor.go`, and it currently doesn't.

Anyways, what user sees is this:

```
> docker run busybox cat /etc/resolv.conf 
nameserver 10.0.2.3
> docker run -e WEAVE_CIDR= busybox cat /etc/resolv.conf
nameserver 172.17.42.1
```

### PR DESCRIPTION
**Pull request by paulbellamy**
Closes #744 
PRed into 0.11 branch this time.

### CODE REVIEW

File: test/620_proxy_entrypoint_command_test.sh [hunk 1]
```diff
@@ -3,27 +3,33 @@
...
-build_image false '["/bin/false"]' ''
-run_container "--entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier"
+build_image $HOST1 false '["/bin/false"]' ''
+run_container $HOST1 "--entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier"
+
+weave_on $HOST2 launch -iprange 10.2.2.0/24
+weave_on $HOST2 launch-proxy --with-ipam
+
+build_image $HOST2 false '["/bin/false"]' ''
+assert_raises "proxy docker_on $HOST2 run --entrypoint='grep' false ^1$ /sys/class/net/ethwe/carrier"
```
Comment (rade) [inline test/620_proxy_entrypoint_command_test.sh]: just a) launch with `-iprange` to begin with, and b) `docker stop` the proxy and re-launch it. That way you can stay on $HOST1 and re-use the `check-ethwe-up` image.
