### PR TITLE
Ensure we have the right modules loaded for weave-npc

### LINKED ISSUE #2726: weave-kube does not work with `dockerd --iptables=false`
This configuration of docker is recommended in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-worker.md; the problem is that we rely on docker to load the `br_netfilter` module, and it doesn't do so when `--iptables=false`.

On further investigation it turns out that loading the module from inside the weave-kube container is pretty straightforward; Alpine's busybox already implements `modprobe`, and other than that we need `-v /lib/modules:/lib/modules` and one of `--privileged` or `--cap-add SYS_MODULE`:

```
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine rmmod br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine lsmod|grep br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine modprobe br_netfilter
$ sudo docker run --cap-add SYS_MODULE -v /lib/modules:/lib/modules -ti alpine lsmod|grep br_netfilter
br_netfilter           24576  0 
bridge                126976  1 br_netfilter
```

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #2726 

At least when `weave-npc` is executed via the `weave-kube` daemonset.  It would be nicer to separate those two concerns, but we already need to know that `weave-npc` is in use when creating the bridge.

### CODE REVIEW

**Comment by bboreham** [comment]
I have tested this by hand, by modifying the Docker daemon parameters to include `--iptables=false` and starting up `weave-kube`.

File: prog/weave-kube/launch.sh [hunk 1]
```diff
@@ -15,6 +15,12 @@ CONN_LIMIT=${CONN_LIMIT:-30}
 # Default for network policy
 EXPECT_NPC=${EXPECT_NPC:-1}
 
+# Ensure we have the required modules for NPC
+if [ "${EXPECT_NPC}" != "0" ]; then
+    modprobe br_netfilter
```
Comment (weitzj) [inline prog/weave-kube/launch.sh]: I am seeing errors like:

`modprobe: module br_netfilter not found in modules.dep`

I guess this feature works only, if the module is **not compiled into** the kernel itself.
See a related discussion https://github.com/kubernetes/kubernetes/issues/12459

Comment (bboreham) [inline prog/weave-kube/launch.sh]: Sorry; we are fixing this in #2821
