### PR TITLE
Silence complaints from http_call when at end of 'weave hide'

### LINKED ISSUE #671: `weave hide` complains when weave isn't running
````
$ weave hide 10.2.1.2/24
weave container is not present. Have you launched it?
$ echo $?
1
````

This got broken by #563.

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #671

### CODE REVIEW

File: test/130_expose_test.sh [hunk 1]
```diff
@@ -29,6 +29,9 @@ check_container_connectivity() {
 
 start_suite "exposing weave network to host"
 
+# idempotence of 'hide', even before we have launched weave
+weave_on1 "hide $EXP/24"
+
```
Comment (rade) [inline test/130_expose_test.sh]: Here's what I had in mind:
````
# expose/hide work prior to launching weave
run_on1   "! $PING $EXP"
weave_on1 "expose  $EXP/24"
run_on1   "  $PING $EXP"
weave_on1 "hide    $EXP/24"
run_on1   "! $PING $EXP"
````

Comment (bboreham) [inline test/130_expose_test.sh]: updated
