### PR TITLE
Fix use of '_' as container ID in claim outside range

### LINKED ISSUE #3003: Duplicate automated IP address assignment
I am executing the following sequence:

```
weave launch \
        --ipalloc-range 10.32.0.0/13 --ipalloc-default-subnet 10.32.0.0/12 \
        --name=::1 --ipalloc-init seed=::1,::2,::3,::4

docker run --name sleep-client -h sleep-client.weave.local -dti \
        --init \
        --net=weave \
        $(weave dns-args) \
        --restart always \
        ubuntu:16.04 \
        sleep 2000

docker run --name sleep-client2 -h sleep-client2.weave.local -dti \
        --init \
        --net=weave --ip=10.40.1.11 \
        $(weave dns-args) \
        --restart always \
        ubuntu:16.04 \
        sleep 2000

docker run --name sleep-client3 -h sleep-client3.weave.local -dti \
        --init \
        --net=weave \
        $(weave dns-args) \
        --restart always \
        ubuntu:16.04 \
        sleep 2000
```

## What you expected to happen?
The idea is that the allocated IP range is split in half for manual and automated IP address assignment. The first and the third containers should get the IP automatically from the 10.32.0.0/13 range. The second has got IP address explicitly assigned from the reserved range for manual assignment.

## What happened?
Duplicate IP address for the second and the third container

```JSON
"DNS": {
    "Domain": "weave.local.",
    "Upstream": [
      "192.168.178.1"
    ],
    "Address": "172.17.0.1:53",
    "TTL": 1,
    "Entries": [
      {
        "Hostname": "sleep-client.weave.local.",
        "Origin": "00:00:00:00:00:01",
        "ContainerID": "8d1e717444252f01f70f527c40274f1512bc3a605e32302720adb02b5a3d741c",
        "Address": "10.32.0.1",
        "Version": 0,
        "Tombstone": 0
      },
      {
        "Hostname": "sleep-client2.weave.local.",
        "Origin": "00:00:00:00:00:01",
        "ContainerID": "841eb894193b95261fece3397b82d931f53d5788edae707664febb75ae098322",
        "Address": "10.40.1.11",
        "Version": 0,
        "Tombstone": 0
      },
      {
        "Hostname": "sleep-client3.weave.local.",
        "Origin": "00:00:00:00:00:01",
        "ContainerID": "0ade68c5b9816f7e32122a4b66643a505f6f4b8c5914464942528d947961393c",
        "Address": "10.40.1.11",
        "Version": 0,
        "Tombstone": 0
      }
    ]
  }
```

## How to reproduce it?
The script above

## Anything else we need to know?
Environment: virtualbox VM.

## Versions:
See with weave 1.9.5 and 1.9.7
docker version 1.13.1

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #3003

### CODE REVIEW

File: ipam/claim.go [hunk 1]
```diff
@@ -51,7 +51,15 @@ func (c *claim) Try(alloc *Allocator) bool {
...
 		// Address not within our universe; assume user knows what they are doing
 		alloc.infof("Address %s claimed by %s - not in our range", c.cidr, c.ident)
-		addOwned()
+		previousOwner := alloc.findOwner(c.cidr.Addr)
+		switch {
+		case previousOwner == "":
+			addOwned()
+		case previousOwner == c.ident: // already owned by this ID
+		case c.ident == api.NoContainerID: // already owned by anonymous container
+		default:
```
Comment (marccarre) [inline ipam/claim.go]: This line [breaks test 300](https://circleci.com/gh/weaveworks/weave/9189):
```
>>> Test /home/ubuntu/src/github.com/weaveworks/weave/test/300_ip_reuse_test.sh finished after 9.6 secs with error: exit status 1
re-using IP addresses (arp cache updating)
01efe0f974a29b6e09bde505709ea774aa1aebbb9ab10d35b8e3a83a339c765c
71109c15f64b01066b4429767cdb6719efcf96218584331388990a971a52db4e
c2
Unable to claim: address 10.2.1.44/24 already in use
```

The code makes sense to me, but do we expect to be able to transparently re-use IPs like test 300 suggests?
Or should we modify the test to (presumably) either:
- `weave_on $HOST1 detach <cid>`? or
- `proxy docker_on $HOST1 stop <cid>`?

Comment (bboreham) [inline ipam/claim.go]: We have just done a `docker stop c2`, so what is happening is IPAM is waiting 30 seconds to see if we restart that container.

We should probably allow a claim from a dead container. I'll try changing the code.

Comment (bboreham) [inline ipam/claim.go]: Fixed
