### PR TITLE
fix connection retry delay calculation logic

### LINKED ISSUE #412: Weave can re-try connections too quickly
Example, from weave logs, where the next attempt occurs 80ms after the previous attempt:

````
20:59:34.196292 ->[104.236.19.13:59829] attempting connection
20:59:34.241031 ->[104.236.19.13:59829] error during connection attempt: dial tcp4 104.236.19.13:59829: connection refused
20:59:34.277109 ->[104.236.19.13:59829] attempting connection
````

This behaviour can generate a lot of uninteresting log lines, making troubleshooting difficult.

From inspection of connection_maker.go, the time intervals are randomized, so could be very tiny.  Suggest we add a minimum delay of a few seconds to the next interval in `tryImmediately()`.

### PR DESCRIPTION
**Pull request by rade**
Fixes #412.

### CODE REVIEW

**Comment by rade** [comment]
I have no idea why that cosmetic change is showing up here, since it's already on master. I think I hadn't pushed it at the time the PR was created.

File: weave [hunk 1]
```diff
@@ -850,13 +850,11 @@ case "$COMMAND" in
             -p $PORT:$CONTAINER_PORT/tcp -p $PORT:$CONTAINER_PORT/udp -e WEAVE_PASSWORD -v /var/run/docker.sock:/var/run/docker.sock \
             $WEAVE_DOCKER_ARGS $IMAGE -iface $CONTAINER_IFNAME -port $CONTAINER_PORT -name "$PEERNAME" -nickname "$(hostname)" $IPRANGE "$@")
         with_container_netns $CONTAINER launch >/dev/null
-
         wait_for_status $CONTAINER_NAME $HTTP_PORT
```
Comment (bboreham) [inline weave]: Change in weave script seems unrelated to rest of PR.

File: router/connection_maker.go [hunk 2]
```diff
@@ -304,14 +304,16 @@ func (cm *ConnectionMaker) attemptConnection(address string, acceptNewPeer bool)
 }
 
 func tryImmediately() (time.Time, time.Duration) {
-	interval := time.Duration(rand.Int63n(int64(InitialInterval)))
-	return time.Now(), interval
+	return time.Now(), InitialInterval
 }
 
+// The delay at the nth retry is a random value in the range
+// [i-i/2,i+i/2], where i = InitialInterval * 1.5^(n-1).
```
Comment (bboreham) [inline router/connection_maker.go]: This comment is only true indirectly, because of the way the function is called.  Maybe `tryAfter` and `tryImmediately` should be methods on `Target*`, and manipulate `tryInterval` directly?
